import { oasdTree } from "./oasdTree.js";
import { maddTree } from "./maddTree.js";
import { szahuTree } from "./szahuTree.js";
import { rtuTree } from "./rtuTree.js";

export const ahuTree = {
  id: "ahu",
  label: "Air Handling Unit",
  abbr: "AHU",
  color: "#0D9488",
  description: "Central air handler selection tree derived from the CCT SQL AHU applications.",
  systemType: "ahu",
  configurations: [
    { id: "mixed-sd", label: "Mixed Air - Single Duct", description: "Supply and return fans with mixed air dampers, single duct distribution" },
    { id: "mixed-dd", label: "Mixed Air - Dual Duct", description: "Mixed air unit with separate cold deck and hot deck supply ducts" },
    { id: "doas", label: "100% Outdoor Air / DOAS", description: "Dedicated outdoor air unit — no return air, ventilation only" },
    { id: "szahu", label: "Single-Zone VAV AHU (G36)", hidden: true },
    { id: "erv-wheel", label: "Energy Recovery - Heat Wheel", description: "Mixed air unit with enthalpy wheel energy recovery" },
    { id: "erv-plate", label: "Energy Recovery - Plate HX", description: "Mixed air unit with air-to-air plate heat exchanger recovery" },
    { id: "erv-rac", label: "Energy Recovery - Run-Around Coil", description: "Mixed air unit with glycol run-around coil energy recovery" },
    { id: "rtu", label: "Rooftop Unit (Packaged)", description: "Packaged rooftop unit with DX cooling and optional gas heat" },
  ],
  mechanicalTreesByConfig: {
    "mixed-dd": maddTree.mechanicalTree,
    doas: oasdTree.mechanicalTree,
    szahu: szahuTree.mechanicalTree,
    rtu: rtuTree.mechanicalTree,
  },
  mechanicalTree: [
    {
      id: "ahu-masd-fans-200",
      label: "Fans",
      scope: "mechanical",
      required: true,
      items: [
        {
          id: "ahu-masd-supply-fan-group-210",
          label: "Supply Fan",
          type: "group",
          items: [
            {
              id: "ahu-masd-supply-fan-type-210",
              label: "Supply Fan Type",
              type: "radio",
              defaultOption: "variable-speed-212",
              options: [
                { id: "single-speed-211", label: "Single Speed" },
                { id: "variable-speed-212", label: "Variable Speed" },
              ],
            },
            { id: "ahu-masd-two-duct-static-pressure-sensors-1346", label: "Two Duct Static Pressure Sensors", type: "check", defaultChecked: false, showWhen: { itemId: "ahu-masd-supply-fan-type-210", value: "variable-speed-212" } },
            { id: "ahu-masd-optimized-control-g36-3000", label: "Optimized Control (G36)", type: "check", defaultChecked: false, hidden: true, showWhen: { itemId: "ahu-masd-supply-fan-type-210", value: "variable-speed-212" } },
            { id: "ahu-masd-dual-supply-fans-6000", label: "Dual Supply Fans", type: "check", defaultChecked: false },
            {
              id: "ahu-masd-dual-supply-fans-mode-6000",
              label: "Dual Supply Fan Mode",
              type: "radio",
              defaultOption: "run-together-6001",
              showWhen: { itemId: "ahu-masd-dual-supply-fans-6000", value: true },
              options: [
                { id: "run-together-6001", label: "Run Together" },
                { id: "lead-lag-6002", label: "Lead/Lag" },
                { id: "run-standby-6003", label: "Run / Standby" },
              ],
            },
            { id: "ahu-masd-supply-fan-status-213", label: "Fan Status", type: "check", defaultChecked: true },
            {
              id: "ahu-masd-supply-loss-airflow-strategy-2200",
              label: "Loss of Airflow Strategy",
              type: "radio",
              defaultOption: "automatic-restart-2210",
              showWhen: { itemId: "ahu-masd-supply-fan-status-213", value: true },
              options: [
                { id: "automatic-restart-2210", label: "Automatic Restart" },
                { id: "manual-restart-2220", label: "Manual Restart" },
              ],
            },
          ],
        },
        {
          id: "ahu-masd-return-fan-group-230",
          label: "Return / Relief Fan",
          type: "group",
          items: [
            { id: "ahu-masd-return-fan-230", label: "Return Fan", type: "check", defaultChecked: false },
            {
              id: "ahu-masd-return-fan-type-230",
              label: "Return Fan Type",
              type: "radio",
              defaultOption: "variable-speed-232",
              showWhen: { itemId: "ahu-masd-return-fan-230", value: true },
              options: [
                { id: "single-speed-231", label: "Single Speed" },
                { id: "variable-speed-232", label: "Variable Speed" },
              ],
            },
            {
              id: "ahu-masd-return-fan-control-2910",
              label: "Return Fan Control",
              type: "radio",
              defaultOption: "track-supply-fan-2930",
              showWhen: { itemId: "ahu-masd-return-fan-230", value: true },
              options: [
                { id: "volume-matching-2910", label: "Volume Matching" },
                { id: "building-static-pressure-2920", label: "Building Static Pressure" },
                { id: "track-supply-fan-2930", label: "Track Supply Fan" },
              ],
            },
            { id: "ahu-masd-dual-return-fans-6005", label: "Dual Return Fans", type: "check", defaultChecked: false, showWhen: { itemId: "ahu-masd-return-fan-230", value: true } },
            { id: "ahu-masd-return-fan-status-233", label: "Fan Status", type: "check", defaultChecked: true, showWhen: { itemId: "ahu-masd-return-fan-230", value: true } },
            {
              id: "ahu-masd-fan-to-start-first-3100",
              label: "Fan to Start First",
              type: "radio",
              defaultOption: "supply-3110",
              showWhen: { itemId: "ahu-masd-return-fan-230", value: true },
              options: [
                { id: "supply-3110", label: "Supply" },
                { id: "return-3120", label: "Return" },
              ],
            },
            { id: "ahu-masd-relief-fan-240", label: "Variable Speed Relief Fan (Bldg Static Press Control)", type: "check", defaultChecked: false },
            { id: "ahu-masd-relief-fan-status-243", label: "Relief Fan Status", type: "check", defaultChecked: true, showWhen: { itemId: "ahu-masd-relief-fan-240", value: true } },
          ],
        },
        {
          id: "ahu-masd-exhaust-fan-group-5800",
          label: "Exhaust Fan",
          type: "group",
          items: [
            { id: "ahu-masd-toilet-exhaust-fan-5810", label: "Toilet Exhaust Fan", type: "check", defaultChecked: false },
            { id: "ahu-masd-general-exhaust-fan-5840", label: "General Exhaust Fan", type: "check", defaultChecked: false },
          ],
        },
      ],
    },
    {
      id: "ahu-masd-economizer-outdoor-air-300",
      label: "Economizer / Outdoor Air",
      scope: "mechanical",
      required: false,
      items: [
        { id: "ahu-masd-economizer-enabled-300", label: "Economizer Damper(s)", type: "check", defaultChecked: false },
        {
          id: "ahu-masd-economizer-type-300",
          label: "Economizer Type",
          type: "radio",
          defaultOption: "common-proportional-mixed-air-damper-output-305",
          showWhen: { itemId: "ahu-masd-economizer-enabled-300", value: true },
          options: [
            { id: "common-proportional-mixed-air-damper-output-305", label: "Common Proportional Mixed Air Damper Output" },
            { id: "separate-proportional-outputs-306", label: "Separate Proportional Outputs (3 AOs)" },
            { id: "ead-rad-proportional-307", label: "EAD & RAD Proportional" },
            { id: "oad-rad-proportional-308", label: "OAD & RAD Proportional" },
          ],
        },
        {
          id: "ahu-masd-economizer-suitability-3230",
          label: "Economizer Suitability",
          type: "radio",
          defaultOption: "outdoor-air-3232",
          showWhen: { itemId: "ahu-masd-economizer-enabled-300", value: true },
          options: [
            { id: "network-command-3231", label: "Network Command" },
            { id: "enthalpy-switch-bi-1630", label: "Enthalpy Switch (BI)" },
            { id: "outdoor-air-3232", label: "Outdoor Air" },
          ],
        },
        {
          id: "ahu-masd-outdoor-air-economizer-type-3237",
          label: "Outdoor Air Economizer Type",
          type: "radio",
          defaultOption: "dry-bulb-temp-economizer-3237",
          showWhen: { itemId: "ahu-masd-economizer-suitability-3230", value: "outdoor-air-3232" },
          options: [
            { id: "dry-bulb-temp-economizer-3237", label: "Dry Bulb Temp Economizer" },
            { id: "temp-enthalpy-economizer-3238", label: "Temp & Enthalpy Economizer" },
            { id: "outdoor-air-versus-return-air-5700", label: "Outdoor Air versus Return Air" },
          ],
        },
        { id: "ahu-masd-co2-min-position-reset-3340", label: "Outdoor and/or Exhaust Air Damper Minimum Position Reset by CO2 Sensor", type: "check", defaultChecked: false, showWhen: { itemId: "ahu-masd-economizer-enabled-300", value: true } },
        { id: "ahu-masd-damper-min-reset-oa-flow-5870", label: "Damper Minimum Position Reset by OA Flow", type: "check", defaultChecked: false, showWhen: { itemId: "ahu-masd-economizer-enabled-300", value: true } },
        { id: "ahu-masd-min-oa-enabled-250", label: "Minimum Outdoor Air Fan and/or Damper", type: "check", defaultChecked: false },
        {
          id: "ahu-masd-min-oa-type-250",
          label: "Minimum Outdoor Air Type",
          type: "radio",
          defaultOption: "single-speed-injection-fan-251",
          showWhen: { itemId: "ahu-masd-min-oa-enabled-250", value: true },
          options: [
            { id: "two-position-damper-343", label: "Two Position Damper" },
            { id: "proportional-damper-342", label: "Proportional Damper" },
            { id: "single-speed-injection-fan-251", label: "Single Speed Injection Fan" },
            { id: "variable-speed-injection-fan-252", label: "Variable Speed Injection Fan" },
          ],
        },
        { id: "ahu-masd-min-oa-fan-status-253", label: "Minimum OA Fan Status", type: "check", defaultChecked: true, showWhen: { itemId: "ahu-masd-min-oa-enabled-250", value: true } },
        { id: "ahu-masd-damper-end-switch-341", label: "Damper End Switch", type: "check", defaultChecked: false, showWhen: { itemId: "ahu-masd-min-oa-enabled-250", value: true } },
      ],
    },
    {
      id: "ahu-masd-temperature-control-strategy-2700",
      label: "Temperature Control Strategy",
      scope: "mechanical",
      required: true,
      items: [
        {
          id: "ahu-masd-temperature-control-strategy-2700",
          label: "Primary Strategy",
          type: "radio",
          defaultOption: "discharge-air-control-2741",
          options: [
            { id: "discharge-air-control-2741", label: "Discharge Air Control" },
            { id: "zone-or-return-control-2730", label: "Zone or Return Control" },
          ],
        },
        { id: "ahu-masd-reset-from-oat-2720", label: "Reset from Outdoor Air Temperature", type: "check", defaultChecked: false, showWhen: { itemId: "ahu-masd-temperature-control-strategy-2700", value: "discharge-air-control-2741" } },
        { id: "ahu-masd-alternate-reset-from-oat-5720", label: "Alternate Reset From Outdoor Air Temperature", type: "check", defaultChecked: false, showWhen: { itemId: "ahu-masd-temperature-control-strategy-2700", value: "discharge-air-control-2741" } },
        { id: "ahu-masd-zone-return-reset-2740", label: "Discharge Air Temperature Reset by Zone or Return", type: "check", defaultChecked: true, showWhen: { itemId: "ahu-masd-temperature-control-strategy-2700", value: "zone-or-return-control-2730" } },
        { id: "ahu-masd-add-return-zone-reset-by-oa-5730", label: "Add Return/Zone Reset by OA", type: "check", defaultChecked: false, showWhen: { itemId: "ahu-masd-temperature-control-strategy-2700", value: "zone-or-return-control-2730" } },
        { id: "ahu-masd-cycle-during-occupied-2736", label: "Cycle During Occupied", type: "check", defaultChecked: false, showWhen: { itemId: "ahu-masd-temperature-control-strategy-2700", value: "zone-or-return-control-2730" } },
        {
          id: "ahu-masd-zone-return-source-2737",
          label: "Zone / Return Source",
          type: "radio",
          defaultOption: "zone-temperature-2738",
          showWhen: { itemId: "ahu-masd-temperature-control-strategy-2700", value: "zone-or-return-control-2730" },
          options: [
            { id: "return-air-temperature-2737", label: "Return Air Temperature" },
            { id: "zone-temperature-2738", label: "Zone Temperature" },
          ],
        },
      ],
    },
    {
      id: "ahu-masd-occupancy-control-2599",
      label: "Occupancy Control",
      scope: "mechanical",
      required: false,
      items: [
        {
          id: "ahu-masd-occupancy-mode-2599",
          label: "Occupancy Mode",
          type: "radio",
          defaultOption: "scheduled-occupancy-2620",
          options: [
            { id: "always-occupied-2600", label: "Always Occupied" },
            { id: "scheduled-occupancy-2620", label: "Scheduled Occupancy" },
          ],
        },
        { id: "ahu-masd-override-support-2630", label: "Override Support", type: "check", defaultChecked: true, showWhen: { itemId: "ahu-masd-occupancy-mode-2599", value: "scheduled-occupancy-2620" } },
        { id: "ahu-masd-occupancy-switch-bi-1640", label: "Occupancy Switch (BI)", type: "check", defaultChecked: false, showWhen: { itemId: "ahu-masd-occupancy-mode-2599", value: "scheduled-occupancy-2620" } },
      ],
    },
    {
      id: "ahu-masd-heat-recovery-400",
      label: "Heat Recovery",
      scope: "mechanical",
      required: false,
      items: [
        {
          id: "hr-type-400",
          label: "Heat Recovery Type",
          type: "radio",
          defaultOption: "none-0",
          options: [
            { id: "none-0", label: "None" },
            { id: "enthalpy-wheel-420", label: "Enthalpy Wheel" },
            { id: "glycol-loop-430", label: "Glycol Loop" },
            { id: "air-to-air-heat-exchanger-441", label: "Air-to-Air Heat Exchanger" },
          ],
        },
        {
          id: "ahu-masd-heat-recovery-enable-type-410",
          label: "Enable Type",
          type: "radio",
          defaultOption: "dry-bulb-compare-411",
          showWhen: { itemId: "hr-type-400", notValue: "none-0" },
          options: [
            { id: "dry-bulb-compare-411", label: "Dry Bulb Compare" },
            { id: "enthalpy-412", label: "Enthalpy" },
            { id: "always-on-442", label: "Always On" },
          ],
        },
        {
          id: "ahu-masd-wheel-speed-420",
          label: "Wheel Speed",
          type: "radio",
          defaultOption: "single-speed-421",
          showWhen: { itemId: "hr-type-400", value: "enthalpy-wheel-420" },
          options: [
            { id: "single-speed-421", label: "Single Speed" },
            { id: "variable-speed-425", label: "Variable Speed" },
          ],
        },
        { id: "ahu-masd-wheel-status-423", label: "Wheel Status", type: "check", defaultChecked: true, showWhen: { itemId: "hr-type-400", value: "enthalpy-wheel-420" } },
        { id: "ahu-masd-glycol-loop-three-way-valve-431", label: "3-Way Valve", type: "check", defaultChecked: true, showWhen: { itemId: "hr-type-400", value: "glycol-loop-430" } },
        { id: "ahu-masd-glycol-loop-pump-status-433", label: "Pump Status", type: "check", defaultChecked: true, showWhen: { itemId: "hr-type-400", value: "glycol-loop-430" } },
        { id: "ahu-masd-air-to-air-bypass-dampers-440", label: "Modulated Bypass Dampers", type: "check", defaultChecked: false, showWhen: { itemId: "hr-type-400", value: "air-to-air-heat-exchanger-441" } },
      ],
    },
    {
      id: "ahu-masd-coils-preheat-500",
      label: "Coils (Preheat)",
      scope: "mechanical",
      required: false,
      items: [
        { id: "ahu-masd-preheat-enabled-600", label: "Preheat", type: "check", defaultChecked: false },
        { id: "ahu-masd-preheat-lockout-650", label: "Preheat Lockout from Outdoor Air", type: "check", defaultChecked: false, showWhen: { itemId: "ahu-masd-preheat-enabled-600", value: true } },
        {
          id: "ahu-masd-preheat-location-610",
          label: "Location",
          type: "radio",
          defaultOption: "mixed-air-612",
          showWhen: { itemId: "ahu-masd-preheat-enabled-600", value: true },
          options: [
            { id: "outdoor-air-611", label: "Outdoor Air" },
            { id: "mixed-air-612", label: "Mixed Air" },
          ],
        },
        {
          id: "ahu-masd-preheat-type-620",
          label: "Preheat Type",
          type: "radio",
          defaultOption: "staged-heating-620",
          showWhen: { itemId: "ahu-masd-preheat-enabled-600", value: true },
          options: [
            { id: "staged-heating-620", label: "Staged Heating" },
            { id: "hot-water-or-steam-630", label: "Hot Water or Steam" },
          ],
        },
      ],
    },
    {
      id: "ahu-masd-coils-cooling-700",
      label: "Coils (Cooling)",
      scope: "mechanical",
      required: false,
      items: [
        { id: "ahu-masd-cooling-enabled-700", label: "Cooling", type: "check", defaultChecked: true },
        { id: "ahu-masd-condensate-alarm-60", label: "Condensate Alarm", type: "check", defaultChecked: false, showWhen: { itemId: "ahu-masd-cooling-enabled-700", value: true } },
        { id: "ahu-masd-cooling-lockout-750", label: "Cooling Lockout from Outdoor Air", type: "check", defaultChecked: true, showWhen: { itemId: "ahu-masd-cooling-enabled-700", value: true } },
        {
          id: "ahu-masd-cooling-type-700",
          label: "Cooling Type",
          type: "radio",
          defaultOption: "chilled-water-720",
          showWhen: { itemId: "ahu-masd-cooling-enabled-700", value: true },
          options: [
            { id: "dx-cooling-710", label: "DX Cooling" },
            { id: "chilled-water-720", label: "Chilled Water" },
          ],
        },
      ],
    },
    {
      id: "ahu-masd-coils-reheat-900",
      label: "Coils (Reheat)",
      scope: "mechanical",
      required: false,
      items: [
        { id: "ahu-masd-reheat-enabled-900", label: "Reheat", type: "check", defaultChecked: false },
        {
          id: "ahu-masd-reheat-type-900",
          label: "Reheat Type",
          type: "radio",
          defaultOption: "staged-heating-910",
          showWhen: { itemId: "ahu-masd-reheat-enabled-900", value: true },
          options: [
            { id: "staged-heating-910", label: "Staged Heating" },
            { id: "hot-water-or-steam-930", label: "Hot Water or Steam" },
          ],
        },
      ],
    },
    {
      id: "ahu-masd-coils-common-1000",
      label: "Coils (Common Heating-Cooling)",
      scope: "mechanical",
      required: false,
      items: [
        { id: "ahu-masd-common-coil-enabled-1000", label: "Common Heating-Cooling", type: "check", defaultChecked: false },
        {
          id: "ahu-masd-common-coil-output-1000",
          label: "Valve / Actuator Type",
          type: "radio",
          defaultOption: "proportional-1010",
          showWhen: { itemId: "ahu-masd-common-coil-enabled-1000", value: true },
          options: [
            { id: "proportional-1010", label: "Proportional" },
            { id: "incremental-1020", label: "Incremental" },
            { id: "two-position-1030", label: "Two Position" },
          ],
        },
      ],
    },
    {
      id: "ahu-masd-humidification-1100",
      label: "Humidification",
      scope: "mechanical",
      required: false,
      items: [
        { id: "ahu-masd-humidification-enabled-1100", label: "Include Humidification", type: "check", defaultChecked: false },
        {
          id: "ahu-masd-humidification-type-1100",
          label: "Humidification Type",
          type: "radio",
          defaultOption: "modulated-packaged-unit-1125",
          showWhen: { itemId: "ahu-masd-humidification-enabled-1100", value: true },
          options: [
            { id: "staged-1110", label: "Staged" },
            { id: "steam-proportional-valve-1120", label: "Steam Proportional Valve" },
            { id: "modulated-packaged-unit-1125", label: "Modulated Packaged Unit" },
          ],
        },
        {
          id: "ahu-masd-humidification-stages-1110",
          label: "Humidification Stages",
          type: "radio",
          defaultOption: "three-stages-1113",
          showWhen: { itemId: "ahu-masd-humidification-type-1100", value: "staged-1110" },
          options: [
            { id: "one-stage-1111", label: "One Stage" },
            { id: "two-stages-1112", label: "Two Stages" },
            { id: "three-stages-1113", label: "Three Stages" },
            { id: "four-stages-1114", label: "Four Stages" },
          ],
        },
        { id: "ahu-masd-humidification-isolation-valve-1122", label: "Isolation Valve", type: "check", defaultChecked: false, showWhen: { itemId: "ahu-masd-humidification-type-1100", value: "steam-proportional-valve-1120" } },
      ],
    },
    {
      id: "ahu-masd-reduce-oa-low-temp-2300",
      label: "Reduce Outdoor Air on Low Temperature",
      scope: "mechanical",
      required: false,
      items: [
        { id: "ahu-masd-reduce-oa-low-temp-2300", label: "Reduce Outdoor Air on Low Temperature", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "ahu-masd-optional-features-2100",
      label: "Optional Features / Platform Flags",
      scope: "mechanical",
      required: false,
      items: [
        { id: "ahu-masd-optional-features-2100", label: "Optional Features / Platform Flags", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "ahu-masd-n2-compatibility-options-15030",
      label: "N2 Compatibility Options",
      scope: "mechanical",
      required: false,
      items: [
        { id: "ahu-masd-n2-compatibility-options-15030", label: "N2 Compatibility Options", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "ahu-masd-optional-sensors-1300",
      label: "Optional Sensors",
      scope: "optional-hardware",
      required: false,
      items: [
        { id: "ahu-masd-optional-sensors-1300", label: "Optional Sensors", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "ahu-masd-optional-equipment-1200",
      label: "Optional Equipment",
      scope: "optional-hardware",
      required: false,
      items: [
        { id: "ahu-masd-optional-equipment-1200", label: "Optional Equipment", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "ahu-masd-monitored-safeties-1500",
      label: "Monitored Safeties",
      scope: "optional-hardware",
      required: false,
      items: [
        { id: "ahu-masd-monitored-safeties-1500", label: "Monitored Safeties", type: "check", defaultChecked: false },
      ],
    },
  ],
};
