const standardCoolingTree = [
  {
    id: "ccp-cooling-system-enable-121",
    label: "Cooling System Enable",
    scope: "mechanical",
    required: true,
    items: [
      { id: "ccp-oa-cooling-lockout-122", label: "OA Cooling Lockout", type: "check", defaultChecked: false },
      { id: "ccp-emergency-shutdown-97", label: "Emergency Shutdown", type: "check", defaultChecked: false },
      { id: "ccp-low-pressure-shutdown-96", label: "Low Pressure Shutdown", type: "check", defaultChecked: false },
    ],
  },
  {
    id: "ccp-chillers-100",
    label: "Chillers",
    scope: "mechanical",
    required: false,
    items: [
      { id: "ccp-chillers-enabled-100", label: "Include Chillers", type: "check", defaultChecked: true },
      {
        id: "ccp-number-of-chillers-110",
        label: "Number of Chillers",
        type: "radio",
        defaultOption: "two-112",
        showWhen: { itemId: "ccp-chillers-enabled-100", value: true },
        options: [
          { id: "one-111", label: "One" },
          { id: "two-112", label: "Two" },
          { id: "three-113", label: "Three" },
          { id: "four-114", label: "Four" },
          { id: "five-115", label: "Five" },
          { id: "six-116", label: "Six" },
          { id: "seven-117", label: "Seven" },
          { id: "eight-118", label: "Eight" },
        ],
      },
      {
        id: "ccp-chiller-sequencing-120",
        label: "Select Type of Sequencing",
        type: "radio",
        defaultOption: "return-water-temp-differential-141",
        showWhen: { itemId: "ccp-chillers-enabled-100", value: true },
        options: [
          { id: "return-water-temp-differential-141", label: "Return Water Temp Differential" },
          { id: "chiller-load-142", label: "Chiller Load" },
          { id: "decouple-loop-flow-143", label: "Decouple Loop Flow" },
          { id: "building-load-144", label: "Building Load" },
        ],
      },
      { id: "ccp-chiller-rotation-runtime-130", label: "Chiller Rotation (Runtime)", type: "check", defaultChecked: false, showWhen: { itemId: "ccp-chillers-enabled-100", value: true } },
      { id: "ccp-chiller-status-150", label: "Chiller Status", type: "check", defaultChecked: true, showWhen: { itemId: "ccp-chillers-enabled-100", value: true } },
      { id: "ccp-chiller-maintenance-switch-160", label: "Chiller Maintenance Switch", type: "check", defaultChecked: false, showWhen: { itemId: "ccp-chillers-enabled-100", value: true } },
    ],
  },
  {
    id: "ccp-condenser-water-system-300",
    label: "Condenser Water System",
    scope: "mechanical",
    required: false,
    items: [
      { id: "ccp-condenser-water-system-enabled-300", label: "Include Condenser Water System", type: "check", defaultChecked: false },
      { id: "ccp-tower-bypass-valve-410", label: "Tower Bypass Valve", type: "check", defaultChecked: true, showWhen: { itemId: "ccp-condenser-water-system-enabled-300", value: true } },
      {
        id: "ccp-cooling-tower-fan-speed-330",
        label: "Cooling Tower Fan Speed",
        type: "radio",
        defaultOption: "single-speed-330",
        showWhen: { itemId: "ccp-condenser-water-system-enabled-300", value: true },
        options: [
          { id: "single-speed-330", label: "Single Speed" },
          { id: "two-speed-340", label: "Two Speed" },
          { id: "three-speed-341", label: "Three Speed" },
          { id: "variable-speed-342", label: "Variable Speed" },
        ],
      },
      { id: "ccp-cooling-tower-fan-status-343", label: "Fan Status", type: "check", defaultChecked: true, showWhen: { itemId: "ccp-condenser-water-system-enabled-300", value: true } },
      { id: "ccp-tower-rotation-runtime-350", label: "Tower Rotation (Runtime)", type: "check", defaultChecked: false, showWhen: { itemId: "ccp-condenser-water-system-enabled-300", value: true } },
      { id: "ccp-isolation-valve-per-tower-370", label: "Isolation Valve per Tower", type: "check", defaultChecked: false, showWhen: { itemId: "ccp-condenser-water-system-enabled-300", value: true } },
    ],
  },
  {
    id: "ccp-secondary-variable-speed-chill-water-pumping-500",
    label: "Secondary Variable Speed Chill Water Pumping",
    scope: "mechanical",
    required: false,
    items: [
      { id: "ccp-secondary-chw-pumping-enabled-500", label: "Include Secondary Variable Speed Chill Water Pumping", type: "check", defaultChecked: false },
      {
        id: "ccp-secondary-chw-pump-count-510",
        label: "Number of Pumps",
        type: "radio",
        defaultOption: "two-pumps-512",
        showWhen: { itemId: "ccp-secondary-chw-pumping-enabled-500", value: true },
        options: [
          { id: "one-pump-511", label: "One Pump" },
          { id: "two-pumps-512", label: "Two Pumps" },
          { id: "three-pumps-513", label: "Three Pumps" },
          { id: "four-pumps-514", label: "Four Pumps" },
          { id: "five-pumps-515", label: "Five Pumps" },
          { id: "six-pumps-516", label: "Six Pumps" },
          { id: "seven-pumps-517", label: "Seven Pumps" },
          { id: "eight-pumps-518", label: "Eight Pumps" },
        ],
      },
      { id: "ccp-secondary-chw-pump-rotation-520", label: "Pump Rotation (Runtime)", type: "check", defaultChecked: true, showWhen: { itemId: "ccp-secondary-chw-pumping-enabled-500", value: true } },
      { id: "ccp-secondary-chw-pump-status-540", label: "Pump Status", type: "check", defaultChecked: true, showWhen: { itemId: "ccp-secondary-chw-pumping-enabled-500", value: true } },
      { id: "ccp-secondary-chw-add-bypass-valve-5346", label: "Add Bypass Valve", type: "check", defaultChecked: false, showWhen: { itemId: "ccp-secondary-chw-pumping-enabled-500", value: true } },
    ],
  },
  {
    id: "ccp-chiller-options-6010",
    label: "Chiller Options",
    scope: "optional-hardware",
    required: false,
    items: [
      { id: "ccp-flow-switch-6021", label: "Flow Switch", type: "check", defaultChecked: false },
      { id: "ccp-flow-sensor-6022", label: "Flow Sensor", type: "check", defaultChecked: false },
      { id: "ccp-entering-water-temp-6023", label: "Entering Water Temp", type: "check", defaultChecked: false },
      { id: "ccp-leaving-water-temp-6024", label: "Leaving Water Temp", type: "check", defaultChecked: false },
      { id: "ccp-chiller-alarm-6040", label: "Chiller Alarm", type: "check", defaultChecked: false },
      { id: "ccp-chiller-setpoint-adjustment-6050", label: "Chiller Setpoint Adjustment", type: "check", defaultChecked: false },
      { id: "ccp-chiller-current-limit-adjustment-6060", label: "Chiller Current Limit Adjustment", type: "check", defaultChecked: false },
    ],
  },
];

const optimizedCoolingTree = [
  {
    id: "ccp-opt-cooling-system-enable-11",
    label: "Cooling System Enable",
    scope: "mechanical",
    required: true,
    items: [
      { id: "ccp-opt-oa-cooling-lockout-12", label: "OA Cooling Lockout", type: "check", defaultChecked: true },
    ],
  },
  {
    id: "ccp-opt-plant-layout-configuration-13",
    label: "Plant layout Configuration",
    scope: "mechanical",
    required: true,
    items: [
      {
        id: "ccp-opt-quantity-of-chillers-1001",
        label: "Quantity Of Chillers",
        type: "radio",
        defaultOption: "two-1020",
        options: [
          { id: "one-1010", label: "One" },
          { id: "two-1020", label: "Two" },
          { id: "three-1030", label: "Three" },
          { id: "four-1040", label: "Four" },
          { id: "five-1050", label: "Five" },
          { id: "six-1060", label: "Six" },
          { id: "seven-1070", label: "Seven" },
          { id: "eight-1080", label: "Eight" },
        ],
      },
      {
        id: "ccp-opt-type-of-chiller-sequencing-1210",
        label: "Type of Chiller Sequencing",
        type: "radio",
        defaultOption: "return-water-temp-differential-1220",
        options: [
          { id: "return-water-temp-differential-1220", label: "Return Water Temp Differential" },
          { id: "chiller-load-1230", label: "Chiller Load" },
          { id: "decouple-loop-flow-1240", label: "Decouple Loop Flow" },
          { id: "building-load-1250", label: "Building Load" },
        ],
      },
      {
        id: "ccp-opt-chw-pump-piping-layout-2001",
        label: "CHW Pump Piping Layout",
        type: "radio",
        defaultOption: "parallel-primary-chw-pumps-2003",
        options: [
          { id: "dedicated-primary-chw-pumps-2002", label: "Dedicated Primary CHW Pumps" },
          { id: "parallel-primary-chw-pumps-2003", label: "Parallel Primary CHW Pumps" },
        ],
      },
      {
        id: "ccp-opt-condenser-pump-piping-layout-3001",
        label: "Condenser Pump Piping Layout",
        type: "radio",
        defaultOption: "parallel-primary-cw-pumps-3003",
        options: [
          { id: "no-cw-piping-air-cooled-3004", label: "No CW Piping (Air Cooled)" },
          { id: "dedicated-primary-cw-pumps-3002", label: "Dedicated Primary CW Pumps" },
          { id: "parallel-primary-cw-pumps-3003", label: "Parallel Primary CW Pumps" },
        ],
      },
      { id: "ccp-opt-secondary-pumping-5002", label: "Secondary Pumping", type: "check", defaultChecked: false },
      { id: "ccp-opt-waterside-economizer-7000", label: "Waterside Economizer", type: "check", defaultChecked: false },
    ],
  },
  {
    id: "ccp-opt-cooling-towers-4000",
    label: "Cooling Towers",
    scope: "mechanical",
    required: false,
    items: [
      { id: "ccp-opt-cooling-towers-enabled-4000", label: "Include Cooling Towers", type: "check", defaultChecked: true },
      { id: "ccp-opt-tower-bypass-valve-4209", label: "Tower Bypass Valve", type: "check", defaultChecked: true, showWhen: { itemId: "ccp-opt-cooling-towers-enabled-4000", value: true } },
      { id: "ccp-opt-makeup-water-4210", label: "Makeup Water", type: "check", defaultChecked: true, showWhen: { itemId: "ccp-opt-cooling-towers-enabled-4000", value: true } },
      { id: "ccp-opt-fan-status-4270", label: "Fan Status", type: "check", defaultChecked: true, showWhen: { itemId: "ccp-opt-cooling-towers-enabled-4000", value: true } },
      { id: "ccp-opt-totalize-tower-fan-runtime-4350", label: "Totalize Tower Fan Runtime", type: "check", defaultChecked: true, showWhen: { itemId: "ccp-opt-cooling-towers-enabled-4000", value: true } },
    ],
  },
  {
    id: "ccp-opt-chiller-options-6010",
    label: "Chiller Options",
    scope: "optional-hardware",
    required: false,
    items: [
      { id: "ccp-opt-flow-switch-6021", label: "Flow Switch", type: "check", defaultChecked: false },
      { id: "ccp-opt-flow-sensor-6022", label: "Flow Sensor", type: "check", defaultChecked: false },
      { id: "ccp-opt-entering-water-temp-6023", label: "Entering Water Temp", type: "check", defaultChecked: true },
      { id: "ccp-opt-leaving-water-temp-6024", label: "Leaving Water Temp", type: "check", defaultChecked: true },
      { id: "ccp-opt-chiller-amperage-6070", label: "Chiller Amperage(s)", type: "check", defaultChecked: false },
    ],
  },
];

export const centralCoolingTree = {
  id: "central-cooling",
  label: "Central Cooling Plant",
  abbr: "CCP",
  color: "#0284C7",
  description: "Chiller plant, cooling tower, and central cooling distribution.",
  systemType: "central-cooling",
  configurations: [
    { id: "standard", label: "Central Cooling" },
    { id: "optimized", label: "Central Cooling with Optimization" },
  ],
  mechanicalTreesByConfig: {
    optimized: optimizedCoolingTree,
  },
  mechanicalTree: standardCoolingTree,
};
