export const centralHeatingTree = {
  id: "central-heating",
  label: "Central Heating Plant",
  abbr: "CHP",
  color: "#DC2626",
  description: "Boiler plant and central heating distribution.",
  systemType: "central-heating",
  configurations: [{ id: "standard", label: "Central Heating" }],
  mechanicalTree: [
    {
      id: "chp-heating-system-enable-98",
      label: "Heating System Enable",
      scope: "mechanical",
      required: true,
      items: [
        { id: "chp-oa-heating-lockout-99", label: "OA Heating Lockout", type: "check", defaultChecked: true },
        { id: "chp-emergency-shutdown-97", label: "Emergency Shutdown", type: "check", defaultChecked: false },
        { id: "chp-low-pressure-shutdown-96", label: "Low Pressure Shutdown", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "chp-hot-water-steam-boilers-100",
      label: "Hot Water/Steam Boilers",
      scope: "mechanical",
      required: false,
      items: [
        { id: "chp-hot-water-steam-boilers-enabled-100", label: "Include Hot Water/Steam Boilers", type: "check", defaultChecked: true },
        {
          id: "chp-number-of-boilers-110",
          label: "Number of Boilers",
          type: "radio",
          defaultOption: "one-111",
          showWhen: { itemId: "chp-hot-water-steam-boilers-enabled-100", value: true },
          options: [
            { id: "one-111", label: "One" },
            { id: "two-292", label: "Two" },
            { id: "three-293", label: "Three" },
            { id: "four-294", label: "Four" },
            { id: "five-295", label: "Five" },
            { id: "six-296", label: "Six" },
            { id: "seven-297", label: "Seven" },
            { id: "eight-298", label: "Eight" },
          ],
        },
        {
          id: "chp-select-type-of-control-200",
          label: "Select Type of Control",
          type: "radio",
          defaultOption: "package-controls-221",
          showWhen: { itemId: "chp-hot-water-steam-boilers-enabled-100", value: true },
          options: [
            { id: "modulate-burners-210", label: "Modulate Burner(s)" },
            { id: "on-off-boilers-by-return-213", label: "On Off Boilers by Return" },
            { id: "package-controls-221", label: "Package Controls" },
          ],
        },
        {
          id: "chp-modulate-burners-control-sensor-263",
          label: "Modulate Burner(s) Control Sensor",
          type: "radio",
          defaultOption: "loop-return-water-temp-261",
          showWhen: { itemId: "chp-select-type-of-control-200", value: "modulate-burners-210" },
          options: [
            { id: "pressure-263", label: "Pressure" },
            { id: "loop-supply-water-temp-265", label: "Loop Supply Water Temp" },
            { id: "loop-return-water-temp-261", label: "Loop Return Water Temp" },
          ],
        },
        {
          id: "chp-package-controls-strategy-262",
          label: "Package Controls Strategy",
          type: "radio",
          defaultOption: "oa-t-264",
          showWhen: { itemId: "chp-select-type-of-control-200", value: "package-controls-221" },
          options: [
            { id: "building-load-262", label: "Building Load" },
            { id: "oa-t-264", label: "OA-T" },
          ],
        },
        { id: "chp-three-way-mixing-valve-212", label: "3-Way Mixing Valve", type: "check", defaultChecked: false, showWhen: { itemId: "chp-select-type-of-control-200", value: "package-controls-221" } },
        { id: "chp-setpoint-adjust-ao-231", label: "Setpoint Adjust AO", type: "check", defaultChecked: false, showWhen: { itemId: "chp-select-type-of-control-200", value: "package-controls-221" } },
        { id: "chp-boiler-rotation-runtime-250", label: "Boiler Rotation (Runtime)", type: "check", defaultChecked: false, showWhen: { itemId: "chp-hot-water-steam-boilers-enabled-100", value: true } },
        { id: "chp-boiler-maintenance-switch-270", label: "Boiler Maintenance Switch", type: "check", defaultChecked: false, showWhen: { itemId: "chp-hot-water-steam-boilers-enabled-100", value: true } },
      ],
    },
    {
      id: "chp-heat-exchangers-600",
      label: "Heat Exchangers",
      scope: "mechanical",
      required: false,
      items: [
        { id: "chp-heat-exchangers-enabled-600", label: "Include Heat Exchangers", type: "check", defaultChecked: false },
        {
          id: "chp-number-of-heat-exchangers-610",
          label: "Number of Heat Exchangers",
          type: "radio",
          defaultOption: "one-611",
          showWhen: { itemId: "chp-heat-exchangers-enabled-600", value: true },
          options: [
            { id: "one-611", label: "One" },
            { id: "two-612", label: "Two" },
          ],
        },
        { id: "chp-with-isolation-valves-613", label: "With Isolation Valves", type: "check", defaultChecked: false, showWhen: { itemId: "chp-number-of-heat-exchangers-610", value: "two-612" } },
        { id: "chp-two-valves-621", label: "Two Valves", type: "check", defaultChecked: false, showWhen: { itemId: "chp-heat-exchangers-enabled-600", value: true } },
        { id: "chp-return-water-low-limit-control-5555", label: "Return Water Low Limit Control", type: "check", defaultChecked: false, showWhen: { itemId: "chp-heat-exchangers-enabled-600", value: true } },
      ],
    },
    {
      id: "chp-secondary-variable-speed-hot-water-pumping-500",
      label: "Secondary Variable Speed Hot Water Pumping",
      scope: "mechanical",
      required: false,
      items: [
        { id: "chp-secondary-hw-pumping-enabled-500", label: "Include Secondary Variable Speed Hot Water Pumping", type: "check", defaultChecked: false },
        {
          id: "chp-secondary-hw-pump-count-510",
          label: "Number of Pumps",
          type: "radio",
          defaultOption: "two-pumps-512",
          showWhen: { itemId: "chp-secondary-hw-pumping-enabled-500", value: true },
          options: [
            { id: "one-pump-511", label: "One Pump" },
            { id: "two-pumps-512", label: "Two Pumps" },
            { id: "three-pumps-513", label: "Three Pumps" },
            { id: "four-pumps-514", label: "Four Pumps" },
            { id: "five-pumps-515", label: "Five Pumps" },
            { id: "six-pumps-516", label: "Six Pumps" },
            { id: "seven-pumps-517", label: "Seven Pumps" },
            { id: "eight-pumps-518", label: "Eight Pumps" },
          ],
        },
        { id: "chp-secondary-hw-pump-rotation-520", label: "Pump Rotation (Runtime)", type: "check", defaultChecked: true, showWhen: { itemId: "chp-secondary-hw-pumping-enabled-500", value: true } },
        { id: "chp-secondary-hw-pump-status-540", label: "Pump Status", type: "check", defaultChecked: true, showWhen: { itemId: "chp-secondary-hw-pumping-enabled-500", value: true } },
        { id: "chp-secondary-hw-add-bypass-valve-5346", label: "Add Bypass Valve", type: "check", defaultChecked: false, showWhen: { itemId: "chp-secondary-hw-pumping-enabled-500", value: true } },
      ],
    },
    {
      id: "chp-zone-loop-control-5900",
      label: "Zone Loop Control",
      scope: "mechanical",
      required: false,
      items: [
        { id: "chp-zone-loop-control-enabled-5900", label: "Include Zone Loop Control", type: "check", defaultChecked: false },
        {
          id: "chp-zone-count-5910",
          label: "Number of Zones",
          type: "radio",
          defaultOption: "two-5912",
          showWhen: { itemId: "chp-zone-loop-control-enabled-5900", value: true },
          options: [
            { id: "one-5911", label: "One" },
            { id: "two-5912", label: "Two" },
            { id: "three-5913", label: "Three" },
            { id: "four-5914", label: "Four" },
            { id: "five-5915", label: "Five" },
            { id: "six-5916", label: "Six" },
            { id: "seven-5917", label: "Seven" },
            { id: "eight-5918", label: "Eight" },
          ],
        },
        { id: "chp-zone-mixing-valve-each-zone-5930", label: "Mixing Valve for Each Zone", type: "check", defaultChecked: false, showWhen: { itemId: "chp-zone-loop-control-enabled-5900", value: true } },
        {
          id: "chp-zone-occupancy-control-5990",
          label: "Occupancy Control",
          type: "radio",
          defaultOption: "always-occupied-5991",
          showWhen: { itemId: "chp-zone-loop-control-enabled-5900", value: true },
          options: [
            { id: "always-occupied-5991", label: "Always Occupied" },
            { id: "scheduled-occupancy-5992", label: "Scheduled Occupancy" },
          ],
        },
      ],
    },
    {
      id: "chp-boiler-options-1010",
      label: "Boiler Options",
      scope: "optional-hardware",
      required: false,
      items: [
        { id: "chp-boiler-status-1011", label: "Boiler Status", type: "check", defaultChecked: true },
        { id: "chp-boiler-general-alarm-1012", label: "Boiler General Alarm", type: "check", defaultChecked: true },
        { id: "chp-boiler-high-temp-alarm-1013", label: "Boiler High Temp Alarm", type: "check", defaultChecked: false },
        { id: "chp-boiler-flow-switch-1014", label: "Boiler Flow Switch", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "chp-general-options-1300",
      label: "General Options",
      scope: "optional-hardware",
      required: false,
      items: [
        { id: "chp-loop-differential-pressure-sensor-1310", label: "Loop Differential Pressure Sensor", type: "check", defaultChecked: false },
        { id: "chp-primary-hw-supply-temperature-1311", label: "Primary HW Supply Temperature", type: "check", defaultChecked: false },
        { id: "chp-primary-hw-return-temperature-1312", label: "Primary HW Return Temperature", type: "check", defaultChecked: false },
        { id: "chp-outdoor-air-temperature-1316", label: "Outdoor Air Temperature", type: "check", defaultChecked: false },
        { id: "chp-outdoor-air-humidity-1317", label: "Outdoor Air Humidity", type: "check", defaultChecked: false },
        { id: "chp-zone-temperature-1319", label: "Zone Temperature", type: "check", defaultChecked: false },
        { id: "chp-mechanical-room-temperature-1318", label: "Mechanical Room Temperature", type: "check", defaultChecked: false },
      ],
    },
  ],
};
