export const fcuTree = {
  id: "fcu",
  label: "Fan Coil Unit",
  abbr: "FCU",
  color: "#7C3AED",
  description: "Fan coil selection tree derived from the CCT SQL fan-coil application.",
  systemType: "fcu",
  configurations: [
    { id: "2-pipe", label: "2-Pipe" },
    { id: "4-pipe", label: "4-Pipe" },
    { id: "ecm", label: "ECM Fan Coil" },
  ],
  mechanicalTree: [
    {
      id: "fcu-supply-fan-4",
      label: "Supply Fan",
      scope: "mechanical",
      required: true,
      items: [
        {
          id: "fcu-supply-fan-type-4",
          label: "Fan Speed",
          type: "radio",
          defaultOption: "single-speed-5",
          options: [
            { id: "single-speed-5", label: "Single Speed" },
            { id: "three-speed-6", label: "Three Speed" },
            { id: "variable-speed-7", label: "Variable Speed" },
            { id: "fan-control-by-others-50", label: "Fan Control by Others" },
          ],
        },
        { id: "fcu-fan-status-8", label: "Fan Status", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "fcu-coils-13",
      label: "Coils",
      scope: "mechanical",
      required: true,
      items: [
        { id: "fcu-cooling-enabled-14", label: "Cooling", type: "check", defaultChecked: true },
        {
          id: "fcu-cooling-group-14",
          label: "Cooling Options",
          type: "group",
          showWhen: { itemId: "fcu-cooling-enabled-14", value: true },
          items: [
            { id: "fcu-cooling-condensate-alarm-60", label: "Condensate Alarm", type: "check", defaultChecked: false },
            {
              id: "fcu-cooling-condensate-shutdown-61",
              label: "Shutdown on Alarm",
              type: "check",
              defaultChecked: false,
              showWhen: { itemId: "fcu-cooling-condensate-alarm-60", value: true },
            },
            {
              id: "fcu-cooling-control-14",
              label: "Cooling Control",
              type: "radio",
              defaultOption: "modulated-16",
              options: [
                { id: "staged-15", label: "Staged" },
                { id: "modulated-16", label: "Modulated" },
              ],
            },
            {
              id: "fcu-cooling-stages-15",
              label: "Cooling Stages",
              type: "radio",
              defaultOption: "two-stages-69",
              showWhen: { itemId: "fcu-cooling-control-14", value: "staged-15" },
              options: [
                { id: "one-stage-68", label: "One Stage" },
                { id: "two-stages-69", label: "Two Stages" },
                { id: "three-stages-70", label: "Three Stages" },
              ],
            },
            {
              id: "fcu-cooling-valve-type-16",
              label: "Cooling Valve Type",
              type: "radio",
              defaultOption: "proportional-74",
              showWhen: { itemId: "fcu-cooling-control-14", value: "modulated-16" },
              options: [
                { id: "proportional-74", label: "Proportional" },
                { id: "incremental-75", label: "Incremental" },
                { id: "two-position-76", label: "Two Position" },
              ],
            },
          ],
        },
        { id: "fcu-heating-enabled-17", label: "Heating", type: "check", defaultChecked: true },
        {
          id: "fcu-heating-group-17",
          label: "Heating Options",
          type: "group",
          showWhen: { itemId: "fcu-heating-enabled-17", value: true },
          items: [
            {
              id: "fcu-heating-control-17",
              label: "Heating Control",
              type: "radio",
              defaultOption: "modulated-19",
              options: [
                { id: "staged-18", label: "Staged" },
                { id: "modulated-19", label: "Modulated" },
              ],
            },
            {
              id: "fcu-heating-stages-18",
              label: "Heating Stages",
              type: "radio",
              defaultOption: "two-stages-72",
              showWhen: { itemId: "fcu-heating-control-17", value: "staged-18" },
              options: [
                { id: "one-stage-71", label: "One Stage" },
                { id: "two-stages-72", label: "Two Stages" },
                { id: "three-stages-73", label: "Three Stages" },
              ],
            },
            {
              id: "fcu-heating-valve-type-19",
              label: "Heating Valve Type",
              type: "radio",
              defaultOption: "proportional-77",
              showWhen: { itemId: "fcu-heating-control-17", value: "modulated-19" },
              options: [
                { id: "proportional-77", label: "Proportional" },
                { id: "incremental-78", label: "Incremental" },
                { id: "two-position-79", label: "Two Position" },
              ],
            },
          ],
        },
        { id: "fcu-common-coil-enabled-23", label: "Common Heating-Cooling", type: "check", defaultChecked: false },
        {
          id: "fcu-common-coil-group-23",
          label: "Common Heating-Cooling Options",
          type: "group",
          showWhen: { itemId: "fcu-common-coil-enabled-23", value: true },
          items: [
            { id: "fcu-common-condensate-alarm-62", label: "Condensate Alarm", type: "check", defaultChecked: false },
            {
              id: "fcu-common-condensate-shutdown-63",
              label: "Shutdown on Alarm",
              type: "check",
              defaultChecked: false,
              showWhen: { itemId: "fcu-common-condensate-alarm-62", value: true },
            },
            {
              id: "fcu-common-valve-type-23",
              label: "Valve Type",
              type: "radio",
              defaultOption: "proportional-83",
              options: [
                { id: "proportional-83", label: "Proportional" },
                { id: "incremental-84", label: "Incremental" },
                { id: "two-position-85", label: "Two Position" },
              ],
            },
            { id: "fcu-summer-winter-changeover-24", label: "Summer-Winter Changeover Switch", type: "check", defaultChecked: false },
          ],
        },
      ],
    },
    {
      id: "fcu-sensors-28",
      label: "Sensors",
      scope: "mechanical",
      required: true,
      items: [
        { id: "fcu-oat-51", label: "Outdoor Air Temperature", type: "check", defaultChecked: false },
        {
          id: "fcu-zone-group-88",
          label: "Zone",
          type: "group",
          items: [
            {
              id: "fcu-zone-temperature-group-89",
              label: "Temperature",
              type: "group",
              items: [
                { id: "fcu-zone-setpoint-adjust-91", label: "Setpoint Adjust", type: "check", defaultChecked: true },
                {
                  id: "fcu-zone-setpoint-adjust-type-92",
                  label: "Setpoint Adjust Type",
                  type: "radio",
                  defaultOption: "common-setpoint-adjust-92",
                  showWhen: { itemId: "fcu-zone-setpoint-adjust-91", value: true },
                  options: [
                    { id: "common-setpoint-adjust-92", label: "Common Setpoint Adjust" },
                    { id: "warm-cool-adjust-93", label: "Warm Cool Adjust" },
                  ],
                },
                { id: "fcu-zone-temp-occ-support-94", label: "Temp Occ Support", type: "check", defaultChecked: false },
                { id: "fcu-zone-fan-speed-adjust-96", label: "Fan Speed Adjust", type: "check", defaultChecked: false },
              ],
            },
            { id: "fcu-zone-humidity-105", label: "Zone Humidity", type: "check", defaultChecked: false },
            { id: "fcu-zone-occupancy-30", label: "Zone Occupancy", type: "check", defaultChecked: false },
          ],
        },
        { id: "fcu-discharge-air-temperature-501", label: "Discharge Air Temperature", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "fcu-misc-107",
      label: "Misc",
      scope: "mechanical",
      required: false,
      items: [
        { id: "fcu-energy-hold-off-switch-31", label: "Energy Hold Off Switch", type: "check", defaultChecked: false },
        { id: "fcu-unit-enable-switch-32", label: "Unit Enable Switch", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "fcu-n2-compatibility-options-15040",
      label: "N2 Compatibility Options",
      scope: "mechanical",
      required: false,
      items: [
        { id: "fcu-n2-enabled-15040", label: "Enable N2 Compatibility Options", type: "check", defaultChecked: false },
        {
          id: "fcu-n2-replacement-15040",
          label: "Replacement Mode",
          type: "radio",
          defaultOption: "replacing-unt-series-controller-15002",
          showWhen: { itemId: "fcu-n2-enabled-15040", value: true },
          options: [
            { id: "replacing-unt-series-controller-15002", label: "Replacing UNT Series Controller" },
          ],
        },
      ],
    },
    {
      id: "fcu-optional-equipment-25",
      label: "Optional Equipment",
      scope: "optional-hardware",
      required: false,
      items: [
        { id: "fcu-filter-switch-26", label: "Filter Switch", type: "check", defaultChecked: false },
        { id: "fcu-lighting-27", label: "Lighting", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "fcu-monitored-safeties-106",
      label: "Monitored Safeties",
      scope: "optional-hardware",
      required: false,
      items: [
        { id: "fcu-discharge-air-smoke-detector-52", label: "Discharge Air Smoke Detector", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "fcu-position-feedback-200",
      label: "Position Feedback",
      scope: "optional-hardware",
      required: false,
      items: [
        {
          id: "fcu-modulated-valve-outputs-group-220",
          label: "Modulated Valve Outputs",
          type: "group",
          items: [
            {
              id: "fcu-modulated-valve-feedback-220",
              label: "Feedback Type",
              type: "radio",
              defaultOption: "no-position-feedback-221",
              options: [
                { id: "no-position-feedback-221", label: "No Position Feedback" },
                { id: "analog-input-per-output-222", label: "Analog Input per Output" },
                { id: "binary-input-per-output-223", label: "Binary Input per Output" },
              ],
            },
          ],
        },
        {
          id: "fcu-two-position-valve-outputs-group-240",
          label: "Two Position Valve Outputs",
          type: "group",
          items: [
            {
              id: "fcu-two-position-valve-feedback-240",
              label: "Feedback Type",
              type: "radio",
              defaultOption: "no-position-feedback-241",
              options: [
                { id: "no-position-feedback-241", label: "No Position Feedback" },
                { id: "binary-input-per-output-242", label: "Binary Input per Output" },
                { id: "two-binary-inputs-per-output-243", label: "Two Binary Inputs per Output" },
              ],
            },
          ],
        },
      ],
    },
    {
      id: "fcu-cycle-during-occupied-36",
      label: "Cycle During Occupied",
      scope: "control",
      required: false,
      items: [{ id: "fcu-cycle-during-occupied-36", label: "Cycle During Occupied", type: "check", defaultChecked: false }],
    },
    {
      id: "fcu-disable-fan-heating-58",
      label: "Disable Fan in Heating Mode",
      scope: "control",
      required: false,
      items: [{ id: "fcu-disable-fan-heating-58", label: "Disable Fan in Heating Mode", type: "check", defaultChecked: false }],
    },
    {
      id: "fcu-fan-status-interlock-heating-56",
      label: "Fan Status Interlock with Staged Heating",
      scope: "control",
      required: false,
      items: [{ id: "fcu-fan-status-interlock-heating-56", label: "Fan Status Interlock with Staged Heating", type: "check", defaultChecked: true }],
    },
    {
      id: "fcu-fan-status-interlock-cooling-57",
      label: "Fan Status Interlock with Staged Cooling",
      scope: "control",
      required: false,
      items: [{ id: "fcu-fan-status-interlock-cooling-57", label: "Fan Status Interlock with Staged Cooling", type: "check", defaultChecked: true }],
    },
    {
      id: "fcu-occupancy-38",
      label: "Occupancy",
      scope: "control",
      required: false,
      items: [
        {
          id: "fcu-occupancy-mode-38",
          label: "Occupancy Mode",
          type: "radio",
          defaultOption: "scheduled-occupancy-38",
          options: [
            { id: "always-occupied-2499", label: "Always Occupied" },
            { id: "scheduled-occupancy-38", label: "Scheduled Occupancy" },
          ],
        },
      ],
    },
    {
      id: "fcu-optional-features-42",
      label: "Optional Features",
      scope: "control",
      required: false,
      items: [
        { id: "fcu-unit-enable-44", label: "Unit Enable", type: "check", defaultChecked: true },
        { id: "fcu-power-fail-restart-59", label: "Power Fail Restart Logic", type: "check", defaultChecked: false },
        { id: "fcu-energy-hold-off-43", label: "Energy Hold Off", type: "check", defaultChecked: false },
        { id: "fcu-network-warmup-cooldown-47", label: "Network Warmup-Cooldown Support", type: "check", defaultChecked: false },
        { id: "fcu-zone-low-limit-48", label: "Zone Low Limit Support", type: "check", defaultChecked: false },
        { id: "fcu-summer-winter-shift-49", label: "Summer-Winter Compensation Setpoint Shift", type: "check", defaultChecked: false },
      ],
    },
  ],
};
