export const maddTree = {
  id: "madd",
  label: "Mixed Air Dual Duct",
  abbr: "MADD",
  color: "#0284C7",
  description: "Top-level mixed-air dual-duct structure derived from the CCT SQL tree.",
  systemType: "ahu",
  configurations: [
    { id: "cold-hot-deck", label: "Cold Deck / Hot Deck" },
    { id: "dual-fan", label: "Dual Fan Dual Duct" },
    { id: "with-heat-recovery", label: "With Heat Recovery" },
  ],
  mechanicalTree: [
    {
      id: "madd-fans-200",
      label: "Fans",
      scope: "mechanical",
      required: true,
      items: [
        {
          id: "madd-supply-fan-group-210",
          label: "Supply Fan",
          type: "group",
          items: [
            {
              id: "madd-supply-fan-type-210",
              label: "Supply Fan Type",
              type: "radio",
              defaultOption: "variable-speed-212",
              options: [
                { id: "single-speed-211", label: "Single Speed" },
                { id: "variable-speed-212", label: "Variable Speed" },
              ],
            },
            { id: "madd-two-duct-static-pressure-sensors-1346", label: "Two Duct Static Pressure Sensors", type: "check", defaultChecked: true, showWhen: { itemId: "madd-supply-fan-type-210", value: "variable-speed-212" } },
            { id: "madd-dual-supply-fans-6000", label: "Dual Supply Fans", type: "check", defaultChecked: false },
            {
              id: "madd-dual-supply-fans-mode-6000",
              label: "Dual Supply Fan Mode",
              type: "radio",
              defaultOption: "run-together-6001",
              showWhen: { itemId: "madd-dual-supply-fans-6000", value: true },
              options: [
                { id: "run-together-6001", label: "Run Together" },
                { id: "lead-lag-6002", label: "Lead/Lag" },
                { id: "run-standby-6003", label: "Run / Standby" },
              ],
            },
            { id: "madd-supply-fan-status-213", label: "Fan Status", type: "check", defaultChecked: true },
            {
              id: "madd-supply-loss-airflow-strategy-2200",
              label: "Loss of Airflow Strategy",
              type: "radio",
              defaultOption: "automatic-restart-2210",
              showWhen: { itemId: "madd-supply-fan-status-213", value: true },
              options: [
                { id: "automatic-restart-2210", label: "Automatic Restart" },
                { id: "manual-restart-2220", label: "Manual Restart" },
              ],
            },
          ],
        },
        {
          id: "madd-return-fan-group-230",
          label: "Return / Relief Fan",
          type: "group",
          items: [
            { id: "madd-return-fan-230", label: "Return Fan", type: "check", defaultChecked: false },
            {
              id: "madd-return-fan-type-230",
              label: "Return Fan Type",
              type: "radio",
              defaultOption: "variable-speed-232",
              showWhen: { itemId: "madd-return-fan-230", value: true },
              options: [
                { id: "single-speed-231", label: "Single Speed" },
                { id: "variable-speed-232", label: "Variable Speed" },
              ],
            },
            {
              id: "madd-return-fan-control-2910",
              label: "Return Fan Control",
              type: "radio",
              defaultOption: "track-supply-fan-2930",
              showWhen: { itemId: "madd-return-fan-230", value: true },
              options: [
                { id: "volume-matching-2910", label: "Volume Matching" },
                { id: "building-static-pressure-2920", label: "Building Static Pressure" },
                { id: "track-supply-fan-2930", label: "Track Supply Fan" },
              ],
            },
            { id: "madd-dual-return-fans-6005", label: "Dual Return Fans", type: "check", defaultChecked: false, showWhen: { itemId: "madd-return-fan-230", value: true } },
            { id: "madd-return-fan-status-233", label: "Fan Status", type: "check", defaultChecked: true, showWhen: { itemId: "madd-return-fan-230", value: true } },
            {
              id: "madd-fan-to-start-first-3100",
              label: "Fan to Start First",
              type: "radio",
              defaultOption: "supply-3110",
              showWhen: { itemId: "madd-return-fan-230", value: true },
              options: [
                { id: "supply-3110", label: "Supply" },
                { id: "return-3120", label: "Return" },
              ],
            },
            { id: "madd-relief-fan-240", label: "Variable Speed Relief Fan (Bldg Static Press Control)", type: "check", defaultChecked: false },
            { id: "madd-relief-fan-status-243", label: "Relief Fan Status", type: "check", defaultChecked: true, showWhen: { itemId: "madd-relief-fan-240", value: true } },
          ],
        },
        {
          id: "madd-exhaust-fan-group-5800",
          label: "Exhaust Fan",
          type: "group",
          items: [
            { id: "madd-toilet-exhaust-fan-5810", label: "Toilet Exhaust Fan", type: "check", defaultChecked: false },
            { id: "madd-general-exhaust-fan-5840", label: "General Exhaust Fan", type: "check", defaultChecked: false },
          ],
        },
      ],
    },
    {
      id: "madd-economizer-dampers-300",
      label: "Economizer Damper(s)",
      scope: "mechanical",
      required: false,
      items: [
        { id: "madd-economizer-enabled-300", label: "Economizer Damper(s)", type: "check", defaultChecked: false },
        {
          id: "madd-economizer-type-300",
          label: "Economizer Type",
          type: "radio",
          defaultOption: "common-proportional-mixed-air-damper-output-305",
          showWhen: { itemId: "madd-economizer-enabled-300", value: true },
          options: [
            { id: "common-proportional-mixed-air-damper-output-305", label: "Common Proportional Mixed Air Damper Output" },
            { id: "separate-proportional-outputs-306", label: "Separate Proportional Outputs (3 AOs)" },
            { id: "ead-rad-proportional-307", label: "EAD & RAD Proportional" },
            { id: "oad-rad-proportional-308", label: "OAD & RAD Proportional" },
          ],
        },
        {
          id: "madd-economizer-suitability-3230",
          label: "Economizer Suitability",
          type: "radio",
          defaultOption: "outdoor-air-3232",
          showWhen: { itemId: "madd-economizer-enabled-300", value: true },
          options: [
            { id: "network-command-3231", label: "Network Command" },
            { id: "enthalpy-switch-bi-1630", label: "Enthalpy Switch (BI)" },
            { id: "outdoor-air-3232", label: "Outdoor Air" },
          ],
        },
        {
          id: "madd-outdoor-air-economizer-type-3237",
          label: "Outdoor Air Economizer Type",
          type: "radio",
          defaultOption: "dry-bulb-temp-economizer-3237",
          showWhen: { itemId: "madd-economizer-suitability-3230", value: "outdoor-air-3232" },
          options: [
            { id: "dry-bulb-temp-economizer-3237", label: "Dry Bulb Temp Economizer" },
            { id: "temp-enthalpy-economizer-3238", label: "Temp & Enthalpy Economizer" },
            { id: "outdoor-air-versus-return-air-5700", label: "Outdoor Air versus Return Air" },
          ],
        },
        { id: "madd-co2-min-position-reset-3340", label: "Outdoor and/or Exhaust Air Damper Minimum Position Reset by CO2 Sensor", type: "check", defaultChecked: false, showWhen: { itemId: "madd-economizer-enabled-300", value: true } },
      ],
    },
    {
      id: "madd-minimum-oa-250",
      label: "Minimum Outdoor Air Fan and/or Damper",
      scope: "mechanical",
      required: false,
      items: [
        { id: "madd-min-oa-enabled-250", label: "Minimum Outdoor Air Fan and/or Damper", type: "check", defaultChecked: false },
        {
          id: "madd-min-oa-type-250",
          label: "Minimum Outdoor Air Type",
          type: "radio",
          defaultOption: "single-speed-injection-fan-251",
          showWhen: { itemId: "madd-min-oa-enabled-250", value: true },
          options: [
            { id: "two-position-damper-343", label: "Two Position Damper" },
            { id: "proportional-damper-342", label: "Proportional Damper" },
            { id: "single-speed-injection-fan-251", label: "Single Speed Injection Fan" },
            { id: "variable-speed-injection-fan-252", label: "Variable Speed Injection Fan" },
          ],
        },
        { id: "madd-min-oa-fan-status-253", label: "Minimum OA Fan Status", type: "check", defaultChecked: true, showWhen: { itemId: "madd-min-oa-enabled-250", value: true } },
        { id: "madd-damper-end-switch-341", label: "Damper End Switch", type: "check", defaultChecked: false, showWhen: { itemId: "madd-min-oa-enabled-250", value: true } },
      ],
    },
    {
      id: "madd-reduce-oa-low-temp-2300",
      label: "Reduce Outdoor Air on Low Temperature",
      scope: "mechanical",
      required: false,
      items: [
        { id: "madd-reduce-oa-low-temp-enabled-2300", label: "Reduce Outdoor Air on Low Temperature", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "madd-temperature-control-2700",
      label: "Temperature Control Strategy",
      scope: "mechanical",
      required: true,
      items: [
        {
          id: "madd-temperature-control-strategy-2700",
          label: "Temperature Control Strategy",
          type: "radio",
          defaultOption: "fixed-hot-cold-deck-temperatures-2750",
          options: [
            { id: "fixed-hot-cold-deck-temperatures-2750", label: "Fixed Hot and/or Cold Deck Temperatures" },
            { id: "hot-cold-deck-reset-from-oat-2760", label: "Hot and/or Cold Deck Temperature Reset from OA-T" },
            { id: "hot-deck-reset-from-rat-2770", label: "Hot Deck Temperature Reset from RA-T" },
          ],
        },
      ],
    },
    {
      id: "madd-occupancy-control-2599",
      label: "Occupancy Control",
      scope: "mechanical",
      required: false,
      items: [
        {
          id: "madd-occupancy-mode-2599",
          label: "Occupancy Mode",
          type: "radio",
          defaultOption: "scheduled-occupancy-2620",
          options: [
            { id: "always-occupied-2600", label: "Always Occupied" },
            { id: "scheduled-occupancy-2620", label: "Scheduled Occupancy" },
          ],
        },
        { id: "madd-override-support-2630", label: "Override Support", type: "check", defaultChecked: true, showWhen: { itemId: "madd-occupancy-mode-2599", value: "scheduled-occupancy-2620" } },
        { id: "madd-occupancy-switch-bi-1640", label: "Occupancy Switch (BI)", type: "check", defaultChecked: false, showWhen: { itemId: "madd-occupancy-mode-2599", value: "scheduled-occupancy-2620" } },
        {
          id: "madd-unoccupied-strategy-2640",
          label: "Unoccupied Strategy",
          type: "radio",
          defaultOption: "off-during-unoccupied-2642",
          showWhen: { itemId: "madd-occupancy-mode-2599", value: "scheduled-occupancy-2620" },
          options: [
            { id: "intermittent-night-operation-2641", label: "Intermittent Night Operation" },
            { id: "off-during-unoccupied-2642", label: "Off during Unoccupied" },
          ],
        },
      ],
    },
    {
      id: "madd-heat-recovery-400",
      label: "Heat Recovery",
      scope: "mechanical",
      required: false,
      items: [
        {
          id: "madd-hr-type-400",
          label: "Heat Recovery Type",
          type: "radio",
          defaultOption: "none-0",
          options: [
            { id: "none-0", label: "None" },
            { id: "enthalpy-wheel-420", label: "Enthalpy Wheel" },
            { id: "glycol-loop-430", label: "Glycol Loop" },
            { id: "air-to-air-heat-exchanger-441", label: "Air-to-Air Heat Exchanger" },
          ],
        },
        {
          id: "madd-heat-recovery-enable-type-410",
          label: "Enable Type",
          type: "radio",
          defaultOption: "dry-bulb-compare-411",
          showWhen: { itemId: "madd-hr-type-400", notValue: "none-0" },
          options: [
            { id: "dry-bulb-compare-411", label: "Dry Bulb Compare" },
            { id: "enthalpy-412", label: "Enthalpy" },
          ],
        },
        {
          id: "madd-wheel-speed-420",
          label: "Wheel Speed",
          type: "radio",
          defaultOption: "single-speed-421",
          showWhen: { itemId: "madd-hr-type-400", value: "enthalpy-wheel-420" },
          options: [
            { id: "single-speed-421", label: "Single Speed" },
            { id: "variable-speed-425", label: "Variable Speed" },
          ],
        },
        { id: "madd-wheel-status-423", label: "Wheel Status", type: "check", defaultChecked: true, showWhen: { itemId: "madd-hr-type-400", value: "enthalpy-wheel-420" } },
        { id: "madd-glycol-loop-three-way-valve-431", label: "3-Way Valve", type: "check", defaultChecked: true, showWhen: { itemId: "madd-hr-type-400", value: "glycol-loop-430" } },
        { id: "madd-glycol-loop-pump-status-433", label: "Pump Status", type: "check", defaultChecked: true, showWhen: { itemId: "madd-hr-type-400", value: "glycol-loop-430" } },
        { id: "madd-air-to-air-bypass-dampers-440", label: "Modulated Bypass Dampers", type: "check", defaultChecked: false, showWhen: { itemId: "madd-hr-type-400", value: "air-to-air-heat-exchanger-441" } },
      ],
    },
    {
      id: "madd-coils-preheat-500",
      label: "Coils (Preheat)",
      scope: "mechanical",
      required: false,
      items: [
        { id: "madd-preheat-enabled-600", label: "Preheat", type: "check", defaultChecked: false },
        { id: "madd-preheat-lockout-650", label: "Preheat Lockout from Outdoor Air", type: "check", defaultChecked: false, showWhen: { itemId: "madd-preheat-enabled-600", value: true } },
        {
          id: "madd-preheat-location-610",
          label: "Location",
          type: "radio",
          defaultOption: "mixed-air-612",
          showWhen: { itemId: "madd-preheat-enabled-600", value: true },
          options: [
            { id: "outdoor-air-611", label: "Outdoor Air" },
            { id: "mixed-air-612", label: "Mixed Air" },
          ],
        },
        {
          id: "madd-preheat-type-620",
          label: "Preheat Type",
          type: "radio",
          defaultOption: "hot-water-or-steam-630",
          showWhen: { itemId: "madd-preheat-enabled-600", value: true },
          options: [
            { id: "staged-heating-620", label: "Staged Heating" },
            { id: "hot-water-or-steam-630", label: "Hot Water or Steam" },
          ],
        },
      ],
    },
    {
      id: "madd-coils-cooling-500",
      label: "Coils (Cooling — Cold Deck)",
      scope: "mechanical",
      required: true,
      items: [
        { id: "madd-cooling-enabled-700", label: "Cold Deck Cooling Coil", type: "check", defaultChecked: true },
        { id: "madd-condensate-alarm-60", label: "Condensate Alarm", type: "check", defaultChecked: false, showWhen: { itemId: "madd-cooling-enabled-700", value: true } },
        { id: "madd-cooling-lockout-750", label: "Cooling Lockout from Outdoor Air", type: "check", defaultChecked: true, showWhen: { itemId: "madd-cooling-enabled-700", value: true } },
        {
          id: "madd-cooling-type-700",
          label: "Cooling Type",
          type: "radio",
          defaultOption: "chilled-water-720",
          showWhen: { itemId: "madd-cooling-enabled-700", value: true },
          options: [
            { id: "dx-cooling-710", label: "DX Cooling" },
            { id: "chilled-water-720", label: "Chilled Water" },
          ],
        },
      ],
    },
    {
      id: "madd-coils-reheat-500",
      label: "Coils (Heating — Hot Deck)",
      scope: "mechanical",
      required: false,
      items: [
        { id: "madd-hot-deck-enabled-900", label: "Hot Deck Heating Coil", type: "check", defaultChecked: true },
        {
          id: "madd-hot-deck-type-900",
          label: "Heating Type",
          type: "radio",
          defaultOption: "hot-water-or-steam-930",
          showWhen: { itemId: "madd-hot-deck-enabled-900", value: true },
          options: [
            { id: "staged-heating-910", label: "Staged Heating" },
            { id: "hot-water-or-steam-930", label: "Hot Water or Steam" },
          ],
        },
        { id: "madd-hot-deck-lockout-950", label: "Heating Lockout from Outdoor Air", type: "check", defaultChecked: false, showWhen: { itemId: "madd-hot-deck-enabled-900", value: true } },
      ],
    },
    {
      id: "madd-coils-common-500",
      label: "Coils (Common Heating-Cooling)",
      scope: "mechanical",
      required: false,
      items: [
        { id: "madd-common-coil-enabled-1000", label: "Common Heating-Cooling Coil", type: "check", defaultChecked: false },
        {
          id: "madd-common-coil-output-1000",
          label: "Valve / Actuator Type",
          type: "radio",
          defaultOption: "proportional-1010",
          showWhen: { itemId: "madd-common-coil-enabled-1000", value: true },
          options: [
            { id: "proportional-1010", label: "Proportional" },
            { id: "incremental-1020", label: "Incremental" },
            { id: "two-position-1030", label: "Two Position" },
          ],
        },
      ],
    },
    {
      id: "madd-humidification-1100",
      label: "Humidification",
      scope: "mechanical",
      required: false,
      items: [
        { id: "madd-humidification-enabled-1100", label: "Include Humidification", type: "check", defaultChecked: false },
        {
          id: "madd-humidification-type-1100",
          label: "Humidification Type",
          type: "radio",
          defaultOption: "modulated-packaged-unit-1125",
          showWhen: { itemId: "madd-humidification-enabled-1100", value: true },
          options: [
            { id: "staged-1110", label: "Staged" },
            { id: "steam-proportional-valve-1120", label: "Steam Proportional Valve" },
            { id: "modulated-packaged-unit-1125", label: "Modulated Packaged Unit" },
          ],
        },
        {
          id: "madd-humidification-stages-1110",
          label: "Humidification Stages",
          type: "radio",
          defaultOption: "three-stages-1113",
          showWhen: { itemId: "madd-humidification-type-1100", value: "staged-1110" },
          options: [
            { id: "one-stage-1111", label: "One Stage" },
            { id: "two-stages-1112", label: "Two Stages" },
            { id: "three-stages-1113", label: "Three Stages" },
            { id: "four-stages-1114", label: "Four Stages" },
          ],
        },
        { id: "madd-humidification-isolation-valve-1122", label: "Isolation Valve", type: "check", defaultChecked: false, showWhen: { itemId: "madd-humidification-type-1100", value: "steam-proportional-valve-1120" } },
      ],
    },
    {
      id: "madd-optional-features-2100",
      label: "Optional Features",
      scope: "mechanical",
      required: false,
      items: [
        { id: "madd-smoke-control-2101", label: "Smoke Control Support (UL-864-UUKL)", type: "check", defaultChecked: false },
        { id: "madd-unit-enable-2110", label: "Unit Enable", type: "check", defaultChecked: false },
        { id: "madd-unit-enable-switch-bi-1650", label: "Unit Enable Switch (BI)", type: "check", defaultChecked: false },
        { id: "madd-power-fail-restart-2120", label: "Power Fail Restart", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "madd-n2-compatibility-options-15030",
      label: "N2 Compatibility Options",
      scope: "mechanical",
      required: false,
      items: [
        {
          id: "madd-n2-compatibility-selection-15000",
          label: "N2 Compatibility Options",
          type: "radio",
          defaultOption: "replacing-ahu-series-controller-15001",
          options: [
            { id: "replacing-ahu-series-controller-15001", label: "Replacing AHU Series Controller" },
            { id: "replacing-unt-series-controller-15002", label: "Replacing UNT Series Controller" },
            { id: "replacing-dx9100-series-controller-15003", label: "Replacing DX9100 Series Controller" },
          ],
        },
      ],
    },
    {
      id: "madd-optional-sensors-1300",
      label: "Optional Sensors",
      scope: "optional-hardware",
      required: false,
      items: [
        { id: "madd-outdoor-air-temp-sensor-1301", label: "Outdoor Air Temperature Sensor", type: "check", defaultChecked: true },
        { id: "madd-outdoor-air-humidity-sensor-1302", label: "Outdoor Air Humidity Sensor", type: "check", defaultChecked: false },
        { id: "madd-mixed-air-temp-sensor-1303", label: "Mixed Air Temperature Sensor", type: "check", defaultChecked: true },
        { id: "madd-cold-deck-discharge-temp-1304", label: "Cold Deck Discharge Air Temperature Sensor", type: "check", defaultChecked: true },
        { id: "madd-hot-deck-discharge-temp-1305", label: "Hot Deck Discharge Air Temperature Sensor", type: "check", defaultChecked: true },
        { id: "madd-return-air-temp-sensor-1306", label: "Return Air Temperature Sensor", type: "check", defaultChecked: false },
        { id: "madd-return-air-humidity-sensor-1307", label: "Return Air Humidity Sensor", type: "check", defaultChecked: false },
        { id: "madd-co2-sensor-1308", label: "CO2 Sensor", type: "check", defaultChecked: false },
        { id: "madd-supply-duct-static-1309", label: "Supply Duct Static Pressure Sensor", type: "check", defaultChecked: false },
        { id: "madd-building-static-pressure-1310", label: "Building Static Pressure Sensor", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "madd-optional-equipment-1200",
      label: "Optional Equipment",
      scope: "optional-hardware",
      required: false,
      items: [
        { id: "madd-filter-switch-1201", label: "Filter Switch", type: "check", defaultChecked: false },
        { id: "madd-filter-dp-sensor-1202", label: "Filter Differential Pressure Sensor", type: "check", defaultChecked: false },
        { id: "madd-lighting-relay-1203", label: "Lighting Relay", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "madd-monitored-safeties-1500",
      label: "Monitored Safeties",
      scope: "optional-hardware",
      required: false,
      items: [
        { id: "madd-discharge-smoke-detector-1501", label: "Discharge Air Smoke Detector", type: "check", defaultChecked: false },
        { id: "madd-return-smoke-detector-1502", label: "Return Air Smoke Detector", type: "check", defaultChecked: false },
        { id: "madd-low-limit-freeze-stat-1503", label: "Low Limit Temperature Switch (Freeze Stat)", type: "check", defaultChecked: false },
        { id: "madd-high-static-pressure-switch-1504", label: "High Static Pressure Switch", type: "check", defaultChecked: false },
        { id: "madd-low-static-pressure-switch-1505", label: "Low Static Pressure Switch", type: "check", defaultChecked: false },
        { id: "madd-fire-dampers-1506", label: "Fire Dampers", type: "check", defaultChecked: false },
        {
          id: "madd-fire-damper-reset-strategy-1507",
          label: "Fire Damper Alarm Reset Strategy",
          type: "radio",
          defaultOption: "automatic-restart-1508",
          showWhen: { itemId: "madd-fire-dampers-1506", value: true },
          options: [
            { id: "automatic-restart-1508", label: "Automatic Restart" },
            { id: "unit-reset-switch-bi-1509", label: "Unit Reset Switch (BI)" },
          ],
        },
      ],
    },
  ],
};
