export const oasdTree = {
  id: "oasd",
  label: "100% Outdoor Air Single Duct",
  abbr: "OASD",
  color: "#0F766E",
  description: "Top-level 100% outdoor air single-duct structure derived from the CCT SQL tree.",
  systemType: "ahu",
  configurations: [
    { id: "doas-neutral", label: "Neutral Air DOAS" },
    { id: "doas-cooling", label: "Cooling Primary DOAS" },
    { id: "doas-heating", label: "Heating / Makeup Air" },
  ],
  mechanicalTree: [
    {
      id: "oasd-fans-200",
      label: "Fans",
      scope: "mechanical",
      required: true,
      items: [
        {
          id: "oasd-supply-fan-group-210",
          label: "Supply Fan",
          type: "group",
          items: [
            {
              id: "oasd-supply-fan-type-210",
              label: "Supply Fan Type",
              type: "radio",
              defaultOption: "variable-speed-212",
              options: [
                { id: "single-speed-211", label: "Single Speed" },
                { id: "variable-speed-212", label: "Variable Speed" },
              ],
            },
            { id: "oasd-duct-static-pressure-sensor-1346", label: "Duct Static Pressure Sensor", type: "check", defaultChecked: false, showWhen: { itemId: "oasd-supply-fan-type-210", value: "variable-speed-212" } },
            { id: "oasd-dual-supply-fans-6000", label: "Dual Supply Fans", type: "check", defaultChecked: false },
            {
              id: "oasd-dual-supply-fans-mode-6000",
              label: "Dual Supply Fan Mode",
              type: "radio",
              defaultOption: "run-together-6001",
              showWhen: { itemId: "oasd-dual-supply-fans-6000", value: true },
              options: [
                { id: "run-together-6001", label: "Run Together" },
                { id: "lead-lag-6002", label: "Lead/Lag" },
                { id: "run-standby-6003", label: "Run / Standby" },
              ],
            },
            { id: "oasd-supply-fan-status-213", label: "Fan Status", type: "check", defaultChecked: true },
            {
              id: "oasd-supply-loss-airflow-strategy-2200",
              label: "Loss of Airflow Strategy",
              type: "radio",
              defaultOption: "automatic-restart-2210",
              showWhen: { itemId: "oasd-supply-fan-status-213", value: true },
              options: [
                { id: "automatic-restart-2210", label: "Automatic Restart" },
                { id: "manual-restart-2220", label: "Manual Restart" },
              ],
            },
          ],
        },
        {
          id: "oasd-exhaust-relief-fan-group-240",
          label: "Exhaust / Relief Fan",
          type: "group",
          items: [
            { id: "oasd-relief-fan-240", label: "Variable Speed Relief Fan (Bldg Static Press Control)", type: "check", defaultChecked: false },
            { id: "oasd-relief-fan-status-243", label: "Relief Fan Status", type: "check", defaultChecked: true, showWhen: { itemId: "oasd-relief-fan-240", value: true } },
            { id: "oasd-toilet-exhaust-fan-5810", label: "Toilet Exhaust Fan", type: "check", defaultChecked: false },
            { id: "oasd-general-exhaust-fan-5840", label: "General Exhaust Fan", type: "check", defaultChecked: false },
          ],
        },
      ],
    },
    {
      id: "oasd-temperature-control-strategy-2700",
      label: "Temperature Control Strategy",
      scope: "mechanical",
      required: true,
      items: [
        {
          id: "oasd-temp-control-strategy-2700",
          label: "Primary Strategy",
          type: "radio",
          defaultOption: "discharge-air-control-2715",
          options: [
            { id: "discharge-air-control-2715", label: "Discharge Air Control" },
            { id: "zone-or-exhaust-control-2716", label: "Zone or Exhaust Control" },
          ],
        },
        { id: "oasd-reset-from-oat-2720", label: "Reset from Outdoor Air Temperature", type: "check", defaultChecked: false, showWhen: { itemId: "oasd-temp-control-strategy-2700", value: "discharge-air-control-2715" } },
        { id: "oasd-alternate-reset-from-oat-5720", label: "Alternate Reset From Outdoor Air Temperature", type: "check", defaultChecked: false, showWhen: { itemId: "oasd-temp-control-strategy-2700", value: "discharge-air-control-2715" } },
        {
          id: "oasd-zone-exhaust-reset-strategy-2716",
          label: "Zone / Exhaust Reset Strategy",
          type: "radio",
          defaultOption: "discharge-air-temp-reset-by-zone-temp-2731",
          showWhen: { itemId: "oasd-temp-control-strategy-2700", value: "zone-or-exhaust-control-2716" },
          options: [
            { id: "discharge-air-temp-reset-by-exhaust-air-temp-2740", label: "Discharge Air Temperature Reset by Exhaust Air Temperature" },
            { id: "discharge-air-temp-reset-by-zone-temp-2731", label: "Discharge Air Temperature Reset by Zone Temperature" },
          ],
        },
        { id: "oasd-exhaust-control-staged-cooling-5733", label: "Exhaust Control of Staged Cooling, Reset of Heating", type: "check", defaultChecked: false, showWhen: { itemId: "oasd-zone-exhaust-reset-strategy-2716", value: "discharge-air-temp-reset-by-exhaust-air-temp-2740" } },
        { id: "oasd-add-exhaust-reset-by-oa-5730", label: "Add Exhaust/Zone Reset by OA", type: "check", defaultChecked: false, showWhen: { itemId: "oasd-zone-exhaust-reset-strategy-2716", value: "discharge-air-temp-reset-by-exhaust-air-temp-2740" } },
        { id: "oasd-setpoint-adjust-1410", label: "Setpoint Adjust", type: "check", defaultChecked: false, showWhen: { itemId: "oasd-zone-exhaust-reset-strategy-2716", value: "discharge-air-temp-reset-by-zone-temp-2731" } },
        {
          id: "oasd-setpoint-adjust-type-1410",
          label: "Setpoint Adjust Type",
          type: "radio",
          defaultOption: "common-setpoint-adjust-1411",
          showWhen: { itemId: "oasd-setpoint-adjust-1410", value: true },
          options: [
            { id: "common-setpoint-adjust-1411", label: "Common Setpoint Adjust" },
            { id: "warm-cool-adjust-1412", label: "Warm Cool Adjust" },
          ],
        },
        { id: "oasd-temp-occ-support-1413", label: "Temp Occ Support", type: "check", defaultChecked: false, showWhen: { itemId: "oasd-zone-exhaust-reset-strategy-2716", value: "discharge-air-temp-reset-by-zone-temp-2731" } },
        { id: "oasd-zone-control-staged-cooling-5732", label: "Zone Control of Staged Cooling, Reset of Heating", type: "check", defaultChecked: false, showWhen: { itemId: "oasd-zone-exhaust-reset-strategy-2716", value: "discharge-air-temp-reset-by-zone-temp-2731" } },
        { id: "oasd-add-zone-reset-by-oa-5731", label: "Add Exhaust/Zone Reset by OA", type: "check", defaultChecked: false, showWhen: { itemId: "oasd-zone-exhaust-reset-strategy-2716", value: "discharge-air-temp-reset-by-zone-temp-2731" } },
        { id: "oasd-summer-winter-comp-shift-2733", label: "Summer/Winter Compensation Setpoint Shift", type: "check", defaultChecked: false, showWhen: { itemId: "oasd-temp-control-strategy-2700", value: "zone-or-exhaust-control-2716" } },
      ],
    },
    {
      id: "oasd-occupancy-control-2599",
      label: "Occupancy Control",
      scope: "mechanical",
      required: false,
      items: [
        {
          id: "oasd-occupancy-mode-2599",
          label: "Occupancy Mode",
          type: "radio",
          defaultOption: "scheduled-occupancy-2620",
          options: [
            { id: "always-occupied-2600", label: "Always Occupied" },
            { id: "scheduled-occupancy-2620", label: "Scheduled Occupancy" },
          ],
        },
        { id: "oasd-override-support-2630", label: "Override Support", type: "check", defaultChecked: true, showWhen: { itemId: "oasd-occupancy-mode-2599", value: "scheduled-occupancy-2620" } },
        { id: "oasd-occupancy-switch-bi-1640", label: "Occupancy Switch (BI)", type: "check", defaultChecked: false, showWhen: { itemId: "oasd-occupancy-mode-2599", value: "scheduled-occupancy-2620" } },
        {
          id: "oasd-unoccupied-strategy-2640",
          label: "Unoccupied Strategy",
          type: "radio",
          defaultOption: "off-during-unoccupied-2642",
          showWhen: { itemId: "oasd-occupancy-mode-2599", value: "scheduled-occupancy-2620" },
          options: [
            { id: "intermittent-night-operation-2641", label: "Intermittent Night Operation" },
            { id: "off-during-unoccupied-2642", label: "Off during Unoccupied" },
          ],
        },
      ],
    },
    {
      id: "oasd-heat-recovery-400",
      label: "Heat Recovery",
      scope: "mechanical",
      required: false,
      items: [
        {
          id: "oasd-hr-type-400",
          label: "Heat Recovery Type",
          type: "radio",
          defaultOption: "none-0",
          options: [
            { id: "none-0", label: "None" },
            { id: "enthalpy-wheel-420", label: "Enthalpy Wheel" },
            { id: "glycol-loop-430", label: "Glycol Loop" },
            { id: "air-to-air-heat-exchanger-441", label: "Air-to-Air Heat Exchanger" },
          ],
        },
        {
          id: "oasd-heat-recovery-enable-type-410",
          label: "Enable Type",
          type: "radio",
          defaultOption: "dry-bulb-compare-411",
          showWhen: { itemId: "oasd-hr-type-400", notValue: "none-0" },
          options: [
            { id: "dry-bulb-compare-411", label: "Dry Bulb Compare" },
            { id: "enthalpy-412", label: "Enthalpy" },
            { id: "always-on-442", label: "Always On" },
          ],
        },
        {
          id: "oasd-wheel-speed-420",
          label: "Wheel Speed",
          type: "radio",
          defaultOption: "single-speed-421",
          showWhen: { itemId: "oasd-hr-type-400", value: "enthalpy-wheel-420" },
          options: [
            { id: "single-speed-421", label: "Single Speed" },
            { id: "variable-speed-425", label: "Variable Speed" },
          ],
        },
        { id: "oasd-wheel-status-423", label: "Wheel Status", type: "check", defaultChecked: true, showWhen: { itemId: "oasd-hr-type-400", value: "enthalpy-wheel-420" } },
        { id: "oasd-glycol-loop-three-way-valve-431", label: "3-Way Valve", type: "check", defaultChecked: true, showWhen: { itemId: "oasd-hr-type-400", value: "glycol-loop-430" } },
        { id: "oasd-glycol-loop-pump-status-433", label: "Pump Status", type: "check", defaultChecked: true, showWhen: { itemId: "oasd-hr-type-400", value: "glycol-loop-430" } },
        { id: "oasd-air-to-air-bypass-dampers-440", label: "Modulated Bypass Dampers", type: "check", defaultChecked: false, showWhen: { itemId: "oasd-hr-type-400", value: "air-to-air-heat-exchanger-441" } },
      ],
    },
    {
      id: "oasd-coils-preheat-500",
      label: "Coils (Preheat)",
      scope: "mechanical",
      required: false,
      items: [
        { id: "oasd-preheat-enabled-600", label: "Preheat", type: "check", defaultChecked: false },
        { id: "oasd-preheat-lockout-650", label: "Preheat Lockout from Outdoor Air", type: "check", defaultChecked: false, showWhen: { itemId: "oasd-preheat-enabled-600", value: true } },
        {
          id: "oasd-preheat-type-620",
          label: "Preheat Type",
          type: "radio",
          defaultOption: "hot-water-or-steam-630",
          showWhen: { itemId: "oasd-preheat-enabled-600", value: true },
          options: [
            { id: "staged-heating-620", label: "Staged Heating" },
            { id: "hot-water-or-steam-630", label: "Hot Water or Steam" },
          ],
        },
      ],
    },
    {
      id: "oasd-coils-cooling-500",
      label: "Coils (Cooling)",
      scope: "mechanical",
      required: false,
      items: [
        { id: "oasd-cooling-enabled-700", label: "Cooling Coil", type: "check", defaultChecked: false },
        { id: "oasd-condensate-alarm-60", label: "Condensate Alarm", type: "check", defaultChecked: false, showWhen: { itemId: "oasd-cooling-enabled-700", value: true } },
        {
          id: "oasd-cooling-type-700",
          label: "Cooling Type",
          type: "radio",
          defaultOption: "chilled-water-720",
          showWhen: { itemId: "oasd-cooling-enabled-700", value: true },
          options: [
            { id: "dx-cooling-710", label: "DX Cooling" },
            { id: "chilled-water-720", label: "Chilled Water" },
          ],
        },
      ],
    },
    {
      id: "oasd-coils-reheat-500",
      label: "Coils (Reheat)",
      scope: "mechanical",
      required: false,
      items: [
        { id: "oasd-reheat-enabled-900", label: "Reheat Coil", type: "check", defaultChecked: false },
        {
          id: "oasd-reheat-type-900",
          label: "Reheat Type",
          type: "radio",
          defaultOption: "hot-water-or-steam-930",
          showWhen: { itemId: "oasd-reheat-enabled-900", value: true },
          options: [
            { id: "staged-heating-910", label: "Staged Heating" },
            { id: "hot-water-or-steam-930", label: "Hot Water or Steam" },
          ],
        },
      ],
    },
    {
      id: "oasd-coils-common-500",
      label: "Coils (Common Heating-Cooling)",
      scope: "mechanical",
      required: false,
      items: [
        { id: "oasd-common-coil-enabled-1000", label: "Common Heating-Cooling Coil", type: "check", defaultChecked: false },
        {
          id: "oasd-common-coil-output-1000",
          label: "Valve / Actuator Type",
          type: "radio",
          defaultOption: "proportional-1010",
          showWhen: { itemId: "oasd-common-coil-enabled-1000", value: true },
          options: [
            { id: "proportional-1010", label: "Proportional" },
            { id: "incremental-1020", label: "Incremental" },
            { id: "two-position-1030", label: "Two Position" },
          ],
        },
      ],
    },
    {
      id: "oasd-humidification-1100",
      label: "Humidification",
      scope: "mechanical",
      required: false,
      items: [
        { id: "oasd-humidification-enabled-1100", label: "Include Humidification", type: "check", defaultChecked: false },
        {
          id: "oasd-humidification-type-1100",
          label: "Humidification Type",
          type: "radio",
          defaultOption: "modulated-packaged-unit-1125",
          showWhen: { itemId: "oasd-humidification-enabled-1100", value: true },
          options: [
            { id: "staged-1110", label: "Staged" },
            { id: "steam-proportional-valve-1120", label: "Steam Proportional Valve" },
            { id: "modulated-packaged-unit-1125", label: "Modulated Packaged Unit" },
            { id: "scrubber-5752", label: "Scrubber" },
          ],
        },
        {
          id: "oasd-humidification-stages-1110",
          label: "Humidification Stages",
          type: "radio",
          defaultOption: "three-stages-1113",
          showWhen: { itemId: "oasd-humidification-type-1100", value: "staged-1110" },
          options: [
            { id: "one-stage-1111", label: "One Stage" },
            { id: "two-stages-1112", label: "Two Stages" },
            { id: "three-stages-1113", label: "Three Stages" },
            { id: "four-stages-1114", label: "Four Stages" },
          ],
        },
        { id: "oasd-humidification-isolation-valve-1122", label: "Isolation Valve", type: "check", defaultChecked: false, showWhen: { itemId: "oasd-humidification-type-1100", value: "steam-proportional-valve-1120" } },
        { id: "oasd-staged-humidifier-status-5750", label: "Humidifier Status", type: "check", defaultChecked: false, showWhen: { itemId: "oasd-humidification-type-1100", value: "staged-1110" } },
        { id: "oasd-packaged-humidifier-status-5751", label: "Humidifier Status", type: "check", defaultChecked: false, showWhen: { itemId: "oasd-humidification-type-1100", value: "modulated-packaged-unit-1125" } },
        { id: "oasd-scrubber-drain-valve-5753", label: "Drain Valve", type: "check", defaultChecked: false, showWhen: { itemId: "oasd-humidification-type-1100", value: "scrubber-5752" } },
        { id: "oasd-scrubber-open-if-inactive-5754", label: "Open valve if scrubber is inactive", type: "check", defaultChecked: false, showWhen: { itemId: "oasd-scrubber-drain-valve-5753", value: true } },
        { id: "oasd-scrubber-open-on-network-input-5755", label: "Open valve on Network Input", type: "check", defaultChecked: false, showWhen: { itemId: "oasd-scrubber-drain-valve-5753", value: true } },
        { id: "oasd-scrubber-humidifier-status-5756", label: "Humidifier Status", type: "check", defaultChecked: false, showWhen: { itemId: "oasd-humidification-type-1100", value: "scrubber-5752" } },
        {
          id: "oasd-humidification-control-sensor-3900",
          label: "Control Sensor",
          type: "radio",
          defaultOption: "zone-humidity-3910",
          showWhen: { itemId: "oasd-humidification-enabled-1100", value: true },
          options: [
            { id: "zone-humidity-3910", label: "Zone Humidity" },
            { id: "exhaust-air-humidity-3920", label: "Exhaust Air Humidity" },
          ],
        },
        { id: "oasd-during-unoccupied-mode-3930", label: "During Unoccupied Mode", type: "check", defaultChecked: false, showWhen: { itemId: "oasd-humidification-control-sensor-3900", value: "zone-humidity-3910" } },
        { id: "oasd-discharge-humidity-high-limit-control-1130", label: "Discharge Humidity High Limit Control", type: "check", defaultChecked: false, showWhen: { itemId: "oasd-humidification-enabled-1100", value: true } },
      ],
    },
    {
      id: "oasd-dehumidification-3800",
      label: "Dehumidification Control",
      scope: "mechanical",
      required: false,
      items: [
        { id: "oasd-dehumidification-enabled-3800", label: "Include Dehumidification Control", type: "check", defaultChecked: false },
        {
          id: "oasd-dehumidification-type-3810",
          label: "Dehumidification Type",
          type: "radio",
          defaultOption: "zone-humidity-3810",
          showWhen: { itemId: "oasd-dehumidification-enabled-3800", value: true },
          options: [
            { id: "zone-humidity-3810", label: "Zone Humidity" },
            { id: "exhaust-air-humidity-3820", label: "Exhaust Air Humidity" },
          ],
        },
      ],
    },
    {
      id: "oasd-optional-features-2100",
      label: "Optional Features",
      scope: "mechanical",
      required: false,
      items: [
        { id: "oasd-smoke-control-2101", label: "Smoke Control Support (UL-864-UUKL)", type: "check", defaultChecked: false },
        { id: "oasd-unit-enable-2110", label: "Unit Enable", type: "check", defaultChecked: false },
        { id: "oasd-unit-enable-switch-bi-1650", label: "Unit Enable Switch (BI)", type: "check", defaultChecked: false },
        { id: "oasd-power-fail-restart-2120", label: "Power Fail Restart", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "oasd-n2-compatibility-options-15030",
      label: "N2 Compatibility Options",
      scope: "mechanical",
      required: false,
      items: [
        {
          id: "oasd-n2-compatibility-selection-15000",
          label: "N2 Compatibility Options",
          type: "radio",
          defaultOption: "replacing-ahu-series-controller-15001",
          options: [
            { id: "replacing-ahu-series-controller-15001", label: "Replacing AHU Series Controller" },
            { id: "replacing-unt-series-controller-15002", label: "Replacing UNT Series Controller" },
            { id: "replacing-dx9100-series-controller-15003", label: "Replacing DX9100 Series Controller" },
          ],
        },
      ],
    },
    {
      id: "oasd-optional-sensors-1300",
      label: "Optional Sensors",
      scope: "optional-hardware",
      required: false,
      items: [
        { id: "oasd-outdoor-air-temp-sensor-1301", label: "Outdoor Air Temperature Sensor", type: "check", defaultChecked: true },
        { id: "oasd-outdoor-air-humidity-sensor-1302", label: "Outdoor Air Humidity Sensor", type: "check", defaultChecked: false },
        { id: "oasd-discharge-air-temp-sensor-1303", label: "Discharge Air Temperature Sensor", type: "check", defaultChecked: true },
        { id: "oasd-discharge-air-humidity-sensor-1304", label: "Discharge Air Humidity Sensor", type: "check", defaultChecked: false },
        { id: "oasd-co2-sensor-1305", label: "CO2 Sensor", type: "check", defaultChecked: false },
        { id: "oasd-duct-static-pressure-1306", label: "Supply Duct Static Pressure Sensor", type: "check", defaultChecked: false },
        { id: "oasd-building-static-pressure-1307", label: "Building Static Pressure Sensor", type: "check", defaultChecked: false },
        { id: "oasd-zone-humidity-sensor-1308", label: "Zone Humidity Sensor", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "oasd-optional-equipment-1200",
      label: "Optional Equipment",
      scope: "optional-hardware",
      required: false,
      items: [
        { id: "oasd-pre-filter-switch-1211", label: "Pre-Filter Switch", type: "check", defaultChecked: false },
        { id: "oasd-pre-filter-dp-sensor-1212", label: "Pre-Filter Differential Pressure Sensor", type: "check", defaultChecked: false },
        { id: "oasd-final-filter-switch-1221", label: "Final Filter Switch", type: "check", defaultChecked: false },
        { id: "oasd-final-filter-dp-sensor-1222", label: "Final Filter Differential Pressure Sensor", type: "check", defaultChecked: false },
        { id: "oasd-exhaust-filter-switch-1224", label: "Exhaust Filter Switch", type: "check", defaultChecked: false },
        { id: "oasd-exhaust-filter-dp-sensor-1225", label: "Exhaust Filter Differential Pressure Sensor", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "oasd-monitored-safeties-1500",
      label: "Monitored Safeties",
      scope: "optional-hardware",
      required: false,
      items: [
        { id: "oasd-discharge-high-static-pressure-switch-1511", label: "Discharge High Static Pressure Switch", type: "check", defaultChecked: false },
        { id: "oasd-discharge-smoke-detector-1512", label: "Discharge Smoke Detector", type: "check", defaultChecked: false },
        { id: "oasd-discharge-low-static-pressure-switch-1513", label: "Discharge Low Static Pressure Switch", type: "check", defaultChecked: false },
        { id: "oasd-exhaust-low-static-pressure-switch-1521", label: "Exhaust Low Static Pressure Switch", type: "check", defaultChecked: false },
        { id: "oasd-exhaust-smoke-detector-1532", label: "Exhaust Smoke Detector", type: "check", defaultChecked: false },
        { id: "oasd-exhaust-high-static-pressure-switch-1523", label: "Exhaust High Static Pressure Switch", type: "check", defaultChecked: false },
        { id: "oasd-low-limit-temp-switch-1540", label: "Low Limit Temperature Switch", type: "check", defaultChecked: false },
        { id: "oasd-high-limit-temp-switch-1550", label: "High Limit Temperature Switch", type: "check", defaultChecked: false },
        { id: "oasd-humidity-alarm-1560", label: "Humidity Alarm", type: "check", defaultChecked: false },
        { id: "oasd-fire-dampers-1506", label: "Fire Dampers", type: "check", defaultChecked: false },
        {
          id: "oasd-fire-damper-count-1570",
          label: "Fire Damper Count",
          type: "radio",
          defaultOption: "one-1571",
          showWhen: { itemId: "oasd-fire-dampers-1506", value: true },
          options: [
            { id: "one-1571", label: "One" },
            { id: "two-1572", label: "Two" },
            { id: "three-1573", label: "Three" },
            { id: "four-1574", label: "Four" },
            { id: "five-1575", label: "Five" },
            { id: "six-1576", label: "Six" },
            { id: "seven-1577", label: "Seven" },
            { id: "eight-1578", label: "Eight" },
          ],
        },
        {
          id: "oasd-fire-damper-reset-strategy-1579",
          label: "Fire Damper Alarm Reset Strategy",
          type: "radio",
          defaultOption: "automatic-restart-1580",
          showWhen: { itemId: "oasd-fire-dampers-1506", value: true },
          options: [
            { id: "automatic-restart-1580", label: "Automatic Restart" },
            { id: "manual-restart-1581", label: "Manual Restart" },
          ],
        },
        { id: "oasd-fire-damper-unit-reset-switch-bi-1582", label: "Unit Reset Switch (BI)", type: "check", defaultChecked: false, showWhen: { itemId: "oasd-fire-damper-reset-strategy-1579", value: "manual-restart-1581" } },
      ],
    },
  ],
};
