export const rtuTree = {
  id: "rtu",
  label: "Rooftop Unit",
  abbr: "RTU",
  color: "#EA580C",
  description: "Rooftop unit selection tree derived from the CCT SQL Air Handling Unit.Rooftop Unit application.",
  systemType: "rtu",
  configurations: [
    { id: "gas-heat", label: "Gas Heat / DX Cool", description: "DX cooling with staged gas furnace heating" },
    { id: "heat-pump", label: "Heat Pump", description: "Reversible refrigerant cycle for both heating and cooling" },
    { id: "cool-only", label: "Cooling Only", description: "DX cooling only — no heating stage" },
  ],
  mechanicalTree: [
    {
      id: "rtu-supply-fan-210",
      label: "Supply Fan",
      scope: "mechanical",
      required: true,
      items: [
        { id: "rtu-temperature-based-variable-speed-1422", label: "Temperature Based Variable Speed", type: "check", defaultChecked: false },
        { id: "rtu-fan-status-213", label: "Fan Status", type: "check", defaultChecked: true },
        {
          id: "rtu-loss-of-airflow-strategy-2200",
          label: "Loss of Airflow Strategy",
          type: "radio",
          defaultOption: "automatic-restart-2210",
          showWhen: { itemId: "rtu-fan-status-213", value: true },
          options: [
            { id: "automatic-restart-2210", label: "Automatic Restart" },
            { id: "manual-restart-2220", label: "Manual Restart" },
          ],
        },
        {
          id: "rtu-unit-reset-switch-1660",
          label: "Unit Reset Switch (BI)",
          type: "check",
          defaultChecked: false,
          showWhen: { itemId: "rtu-loss-of-airflow-strategy-2200", value: "manual-restart-2220" },
        },
        {
          id: "rtu-exhaust-fan-group-5800",
          label: "Exhaust Fan",
          type: "group",
          items: [
            { id: "rtu-toilet-exhaust-fan-5810", label: "Toilet Exhaust Fan", type: "check", defaultChecked: false },
            { id: "rtu-general-exhaust-fan-5840", label: "General Exhaust Fan", type: "check", defaultChecked: false },
          ],
        },
      ],
    },
    {
      id: "rtu-economizer-dampers-300",
      label: "Economizer Damper(s)",
      scope: "mechanical",
      required: false,
      items: [
        { id: "rtu-economizer-enabled-300", label: "Include Economizer", type: "check", defaultChecked: false },
        {
          id: "rtu-economizer-type-300",
          label: "Economizer Type",
          type: "radio",
          defaultOption: "common-proportional-mixed-air-damper-output-305",
          showWhen: { itemId: "rtu-economizer-enabled-300", value: true },
          options: [
            { id: "common-proportional-mixed-air-damper-output-305", label: "Common Proportional Mixed Air Damper Output" },
            { id: "packaged-economizer-enable-309", label: "Packaged Economizer Enable (BO)" },
          ],
        },
        {
          id: "rtu-economizer-suitability-3230",
          label: "Economizer Suitability",
          type: "radio",
          defaultOption: "outdoor-air-3232",
          showWhen: { itemId: "rtu-economizer-enabled-300", value: true },
          options: [
            { id: "network-command-3231", label: "Network Command" },
            { id: "enthalpy-switch-bi-1630", label: "Enthalpy Switch (BI)" },
            { id: "outdoor-air-3232", label: "Outdoor Air" },
          ],
        },
        {
          id: "rtu-outdoor-air-economizer-type-3237",
          label: "Outdoor Air Economizer Type",
          type: "radio",
          defaultOption: "dry-bulb-temp-economizer-3237",
          showWhen: { itemId: "rtu-economizer-suitability-3230", value: "outdoor-air-3232" },
          options: [
            { id: "dry-bulb-temp-economizer-3237", label: "Dry Bulb Temp Economizer" },
            { id: "temp-enthalpy-economizer-3238", label: "Temp & Enthalpy Economizer" },
          ],
        },
        { id: "rtu-mixed-air-damper-co2-reset-3340", label: "Mixed Air Damper Minimum Position Reset by CO2 Sensor", type: "check", defaultChecked: false, showWhen: { itemId: "rtu-economizer-enabled-300", value: true } },
        { id: "rtu-reduce-oa-low-temp-2300", label: "Reduce Outdoor Air on Low Temperature", type: "check", defaultChecked: false, showWhen: { itemId: "rtu-economizer-enabled-300", value: true } },
      ],
    },
    {
      id: "rtu-temperature-control-strategy-2700",
      label: "Temperature Control Strategy",
      scope: "mechanical",
      required: true,
      items: [
        {
          id: "rtu-temperature-control-strategy-2700",
          label: "Primary Strategy",
          type: "radio",
          defaultOption: "zone-or-return-control-2730",
          options: [
            { id: "discharge-air-control-2741", label: "Discharge Air Control" },
            { id: "zone-or-return-control-2730", label: "Zone or Return Control" },
          ],
        },
        { id: "rtu-discharge-air-reset-oat-2720", label: "Reset from Outdoor Air Temperature", type: "check", defaultChecked: false, showWhen: { itemId: "rtu-temperature-control-strategy-2700", value: "discharge-air-control-2741" } },
        { id: "rtu-zone-return-reset-2740", label: "Discharge Air Temperature Reset by Zone or Return", type: "check", defaultChecked: false, showWhen: { itemId: "rtu-temperature-control-strategy-2700", value: "zone-or-return-control-2730" } },
        { id: "rtu-cycle-during-occupied-2736", label: "Cycle During Occupied", type: "check", defaultChecked: false, showWhen: { itemId: "rtu-temperature-control-strategy-2700", value: "zone-or-return-control-2730" } },
        {
          id: "rtu-zone-return-sensor-2737",
          label: "Zone / Return Source",
          type: "radio",
          defaultOption: "zone-temperature-2738",
          showWhen: { itemId: "rtu-temperature-control-strategy-2700", value: "zone-or-return-control-2730" },
          options: [
            { id: "return-air-temperature-2737", label: "Return Air Temperature" },
            { id: "zone-temperature-2738", label: "Zone Temperature" },
          ],
        },
        { id: "rtu-summer-winter-setpoint-shift-2733", label: "Summer/Winter Compensation Setpoint Shift", type: "check", defaultChecked: false, showWhen: { itemId: "rtu-temperature-control-strategy-2700", value: "zone-or-return-control-2730" } },
      ],
    },
    {
      id: "rtu-occupancy-control-2599",
      label: "Occupancy Control",
      scope: "mechanical",
      required: false,
      items: [
        {
          id: "rtu-occupancy-mode-2599",
          label: "Occupancy Mode",
          type: "radio",
          defaultOption: "scheduled-occupancy-2620",
          options: [
            { id: "always-occupied-2600", label: "Always Occupied" },
            { id: "scheduled-occupancy-2620", label: "Scheduled Occupancy" },
          ],
        },
        { id: "rtu-override-support-2630", label: "Override Support", type: "check", defaultChecked: true, showWhen: { itemId: "rtu-occupancy-mode-2599", value: "scheduled-occupancy-2620" } },
        { id: "rtu-occupancy-switch-bi-1640", label: "Occupancy Switch (BI)", type: "check", defaultChecked: false, showWhen: { itemId: "rtu-occupancy-mode-2599", value: "scheduled-occupancy-2620" } },
        {
          id: "rtu-unoccupied-strategy-2640",
          label: "Unoccupied Strategy",
          type: "radio",
          defaultOption: "intermittent-night-operation-2641",
          showWhen: { itemId: "rtu-occupancy-mode-2599", value: "scheduled-occupancy-2620" },
          options: [
            { id: "intermittent-night-operation-2641", label: "Intermittent Night Operation" },
            { id: "off-during-unoccupied-2642", label: "Off during Unoccupied" },
          ],
        },
      ],
    },
    {
      id: "rtu-coils-500",
      label: "Coils",
      scope: "mechanical",
      required: true,
      items: [
        { id: "rtu-cooling-enabled-700", label: "Cooling", type: "check", defaultChecked: true },
        {
          id: "rtu-cooling-group-700",
          label: "Cooling Options",
          type: "group",
          showWhen: { itemId: "rtu-cooling-enabled-700", value: true },
          items: [
            { id: "rtu-condensate-alarm-60", label: "Condensate Alarm", type: "check", defaultChecked: false },
            { id: "rtu-cooling-lockout-750", label: "Cooling Lockout from Outdoor Air", type: "check", defaultChecked: false },
            {
              id: "rtu-cooling-type-700",
              label: "Cooling Type",
              type: "radio",
              defaultOption: "dx-cooling-710",
              options: [
                { id: "dx-cooling-710", label: "DX Cooling" },
                { id: "chilled-water-720", label: "Chilled Water" },
              ],
            },
            {
              id: "rtu-dx-cooling-stages-699",
              label: "Number of Stages",
              type: "radio",
              defaultOption: "one-stage-701",
              showWhen: { itemId: "rtu-cooling-type-700", value: "dx-cooling-710" },
              options: [
                { id: "one-stage-701", label: "One Stage" },
                { id: "two-stages-702", label: "Two Stages" },
                { id: "three-stages-703", label: "Three Stages" },
                { id: "four-stages-704", label: "Four Stages" },
                { id: "five-stages-705", label: "Five Stages" },
                { id: "six-stages-706", label: "Six Stages" },
                { id: "seven-stages-707", label: "Seven Stages" },
                { id: "eight-stages-708", label: "Eight Stages" },
              ],
            },
            {
              id: "rtu-chilled-water-actuator-720",
              label: "Chilled Water Actuator",
              type: "radio",
              defaultOption: "proportional-actuator-709",
              showWhen: { itemId: "rtu-cooling-type-700", value: "chilled-water-720" },
              options: [
                { id: "proportional-actuator-709", label: "Proportional Actuator" },
                { id: "incremental-actuator-715", label: "Incremental Actuator" },
                { id: "two-position-actuator-711", label: "Two Position Actuator" },
              ],
            },
          ],
        },
        { id: "rtu-heating-enabled-900", label: "Heating", type: "check", defaultChecked: true },
        {
          id: "rtu-heating-group-900",
          label: "Heating Options",
          type: "group",
          showWhen: { itemId: "rtu-heating-enabled-900", value: true },
          items: [
            { id: "rtu-heating-lockout-950", label: "Heating Lockout from Outdoor Air", type: "check", defaultChecked: false },
            {
              id: "rtu-heat-type-900",
              label: "Heating Type",
              type: "radio",
              defaultOption: "staged-heating-910",
              options: [
                { id: "staged-heating-910", label: "Staged Heating" },
                { id: "hot-water-or-steam-930", label: "Hot Water or Steam" },
                { id: "none-0", label: "None" },
              ],
            },
            {
              id: "rtu-staged-heating-stages-901",
              label: "Number of Stages",
              type: "radio",
              defaultOption: "two-stages-903",
              showWhen: { itemId: "rtu-heat-type-900", value: "staged-heating-910" },
              options: [
                { id: "one-stage-902", label: "One Stage" },
                { id: "two-stages-903", label: "Two Stages" },
                { id: "three-stages-904", label: "Three Stages" },
                { id: "four-stages-905", label: "Four Stages" },
                { id: "five-stages-906", label: "Five Stages" },
                { id: "six-stages-907", label: "Six Stages" },
                { id: "seven-stages-908", label: "Seven Stages" },
                { id: "eight-stages-909", label: "Eight Stages" },
              ],
            },
            {
              id: "rtu-hot-water-output-930",
              label: "Hot Water / Steam Output",
              type: "radio",
              defaultOption: "proportional-output-922",
              showWhen: { itemId: "rtu-heat-type-900", value: "hot-water-or-steam-930" },
              options: [
                { id: "proportional-output-922", label: "Proportional Output" },
                { id: "incremental-output-923", label: "Incremental Output" },
              ],
            },
          ],
        },
      ],
    },
    {
      id: "rtu-humidification-1100",
      label: "Humidification",
      scope: "mechanical",
      required: false,
      items: [
        { id: "rtu-humidification-enabled-1100", label: "Include Humidification", type: "check", defaultChecked: false },
        {
          id: "rtu-humidification-type-1100",
          label: "Humidification Type",
          type: "radio",
          defaultOption: "modulated-packaged-unit-1125",
          showWhen: { itemId: "rtu-humidification-enabled-1100", value: true },
          options: [
            { id: "staged-1110", label: "Staged" },
            { id: "steam-proportional-valve-1120", label: "Steam Proportional Valve" },
            { id: "modulated-packaged-unit-1125", label: "Modulated Packaged Unit" },
          ],
        },
        {
          id: "rtu-humidification-stages-1110",
          label: "Humidification Stages",
          type: "radio",
          defaultOption: "three-stages-1113",
          showWhen: { itemId: "rtu-humidification-type-1100", value: "staged-1110" },
          options: [
            { id: "one-stage-1111", label: "One Stage" },
            { id: "two-stages-1112", label: "Two Stages" },
            { id: "three-stages-1113", label: "Three Stages" },
            { id: "four-stages-1114", label: "Four Stages" },
          ],
        },
        { id: "rtu-humidification-isolation-valve-1122", label: "Isolation Valve", type: "check", defaultChecked: false, showWhen: { itemId: "rtu-humidification-type-1100", value: "steam-proportional-valve-1120" } },
      ],
    },
    {
      id: "rtu-dehumidification-control-3800",
      label: "Dehumidification Control",
      scope: "mechanical",
      required: false,
      items: [
        { id: "rtu-dehumidification-enabled-3800", label: "Include Dehumidification", type: "check", defaultChecked: false },
        {
          id: "rtu-dehumidification-sensor-3800",
          label: "Humidity Source",
          type: "radio",
          defaultOption: "zone-humidity-3810",
          showWhen: { itemId: "rtu-dehumidification-enabled-3800", value: true },
          options: [
            { id: "zone-humidity-3810", label: "Zone Humidity" },
            { id: "return-air-humidity-3820", label: "Return Air Humidity" },
          ],
        },
        { id: "rtu-hot-gas-reheat-3830", label: "Activate Hot Gas Reheat during Dehumidification", type: "check", defaultChecked: true, showWhen: { itemId: "rtu-dehumidification-enabled-3800", value: true } },
      ],
    },
    {
      id: "rtu-optional-features-2100",
      label: "Optional Features",
      scope: "mechanical",
      required: false,
      items: [
        { id: "rtu-smoke-control-support-2105", label: "Smoke Control Support (UL-864-UUKL)", type: "check", defaultChecked: false },
        { id: "rtu-unit-enable-2110", label: "Unit Enable", type: "check", defaultChecked: false },
        { id: "rtu-unit-enable-switch-bi-1650", label: "Unit Enable Switch (BI)", type: "check", defaultChecked: false },
        { id: "rtu-power-fail-restart-2120", label: "Power Fail Restart", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "rtu-n2-compatibility-options-15030",
      label: "N2 Compatibility Options",
      scope: "mechanical",
      required: false,
      items: [
        { id: "rtu-n2-enabled-15030", label: "Enable N2 Compatibility Options", type: "check", defaultChecked: false },
        {
          id: "rtu-n2-replacement-15030",
          label: "Replacement Mode",
          type: "radio",
          defaultOption: "replacing-unt-series-controller-15002",
          showWhen: { itemId: "rtu-n2-enabled-15030", value: true },
          options: [
            { id: "replacing-unt-series-controller-15002", label: "Replacing UNT Series Controller" },
          ],
        },
      ],
    },
    {
      id: "rtu-optional-sensors-1300",
      label: "Optional Sensors",
      scope: "optional-hardware",
      required: false,
      items: [
        { id: "rtu-position-feedback-201", label: "Position Feedback", type: "check", defaultChecked: false },
        { id: "rtu-outdoor-air-sensors-1310", label: "Outdoor Air", type: "check", defaultChecked: false },
        { id: "rtu-mixed-air-sensors-1320", label: "Mixed Air", type: "check", defaultChecked: false },
        { id: "rtu-discharge-air-sensors-1340", label: "Discharge Air", type: "check", defaultChecked: false },
        { id: "rtu-return-air-sensors-1350", label: "Return Air", type: "check", defaultChecked: false },
        { id: "rtu-zone-sensors-1400", label: "Zone", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "rtu-optional-equipment-1200",
      label: "Optional Equipment",
      scope: "optional-hardware",
      required: false,
      items: [
        { id: "rtu-pre-filter-1210", label: "Pre-Filter", type: "check", defaultChecked: false },
        { id: "rtu-final-filter-1220", label: "Final Filter", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "rtu-monitored-safeties-1500",
      label: "Monitored Safeties",
      scope: "optional-hardware",
      required: false,
      items: [
        { id: "rtu-discharge-safeties-1510", label: "Discharge", type: "check", defaultChecked: false },
        { id: "rtu-return-smoke-1520", label: "Return", type: "check", defaultChecked: false },
        { id: "rtu-low-limit-switch-1540", label: "Low Limit Temperature Switch", type: "check", defaultChecked: false },
        { id: "rtu-high-limit-switch-1550", label: "High Limit Temperature Switch", type: "check", defaultChecked: false },
      ],
    },
  ],
};
