export const simpleCentralPlantTree = {
  id: "simple-plant",
  label: "Simple Central Plant",
  abbr: "SCP",
  color: "#059669",
  description: "Combined heating and cooling plant — simplified single-loop configuration.",
  systemType: "simple-plant",
  configurations: [{ id: "standard", label: "Simple Central Plant" }],
  mechanicalTree: [
    {
      id: "scp-plant-layout-configuration-13",
      label: "Plant Layout Configuration",
      scope: "mechanical",
      required: true,
      items: [
        {
          id: "scp-plant-layout-type-13",
          label: "Plant Type",
          type: "radio",
          defaultOption: "four-pipe-plant-16",
          options: [
            { id: "cooling-only-plant-14", label: "Cooling Only Plant" },
            { id: "heating-only-plant-15", label: "Heating Only Plant" },
            { id: "four-pipe-plant-16", label: "Four Pipe Plant (Heating and Cooling)" },
            { id: "two-pipe-plant-17", label: "Two Pipe Plant (Heating and Cooling)" },
          ],
        },
        { id: "scp-water-source-heat-pump-loop-18", label: "Water Source Heat Pump Loop", type: "check", defaultChecked: false, showWhen: { itemId: "scp-plant-layout-type-13", value: "two-pipe-plant-17" } },
        { id: "scp-one-chiller-1010", label: "One Chiller", type: "check", defaultChecked: true },
        { id: "scp-hot-water-boiler-8010", label: "Hot Water Boiler", type: "check", defaultChecked: true },
        { id: "scp-steam-boiler-8020", label: "Steam Boiler", type: "check", defaultChecked: false },
        { id: "scp-steam-heat-exchanger-8030", label: "Steam Heat Exchanger", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "scp-cooling-system-1000",
      label: "Cooling System",
      scope: "mechanical",
      required: false,
      items: [
        { id: "scp-chiller-status-1240", label: "Chiller Status", type: "check", defaultChecked: true },
        { id: "scp-primary-chw-pump-status-2240", label: "Primary Chill Water Pump Status", type: "check", defaultChecked: true },
        { id: "scp-primary-chw-pump-rotation-2200", label: "Pump Rotation (Runtime)", type: "check", defaultChecked: false },
        { id: "scp-primary-chw-bypass-valve-2310", label: "Bypass Valve with Diff Pressure Sensor", type: "check", defaultChecked: false },
        { id: "scp-condenser-water-pump-status-3240", label: "Condenser Water Pump Status", type: "check", defaultChecked: true },
        { id: "scp-cooling-tower-fan-status-4240", label: "Cooling Tower Fan Status", type: "check", defaultChecked: true },
      ],
    },
    {
      id: "scp-heating-system-8000",
      label: "Heating System",
      scope: "mechanical",
      required: false,
      items: [
        {
          id: "scp-boiler-control-type-8002",
          label: "Boiler Control Type",
          type: "radio",
          defaultOption: "package-controls-oa-t-8130",
          options: [
            { id: "modulate-burners-8110", label: "Modulate Burner(s)" },
            { id: "on-off-boilers-by-return-8120", label: "On Off Boilers by Return" },
            { id: "package-controls-oa-t-8130", label: "Package Controls OA-T" },
          ],
        },
        { id: "scp-primary-hw-pump-status-9240", label: "Primary Hot Water Pump Status", type: "check", defaultChecked: true },
        { id: "scp-primary-hw-pump-rotation-9200", label: "Pump Rotation (Runtime)", type: "check", defaultChecked: false },
        { id: "scp-primary-hw-bypass-valve-9310", label: "Bypass Valve with Diff Pressure Sensor", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "scp-two-pipe-system-7000",
      label: "2 Pipe System",
      scope: "mechanical",
      required: false,
      items: [
        { id: "scp-primary-heating-cooling-pump-status-7240", label: "Pump status", type: "check", defaultChecked: true },
        { id: "scp-primary-heating-cooling-pump-rotation-7200", label: "Pump Rotation (Runtime)", type: "check", defaultChecked: false },
        { id: "scp-primary-heating-cooling-bypass-valve-7310", label: "Bypass Valve with Diff Pressure Sensor", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "scp-chiller-options-6010",
      label: "Chiller Options",
      scope: "optional-hardware",
      required: false,
      items: [
        { id: "scp-flow-switch-6021", label: "Flow Switch", type: "check", defaultChecked: false },
        { id: "scp-flow-sensor-6022", label: "Flow Sensor", type: "check", defaultChecked: false },
        { id: "scp-entering-water-temp-6023", label: "Entering Water Temp", type: "check", defaultChecked: false },
        { id: "scp-leaving-water-temp-6024", label: "Leaving Water Temp", type: "check", defaultChecked: false },
        { id: "scp-chiller-alarm-6040", label: "Chiller Alarm", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "scp-heating-system-options-11010",
      label: "Heating System Options",
      scope: "optional-hardware",
      required: false,
      items: [
        { id: "scp-boiler-status-11011", label: "Boiler Status", type: "check", defaultChecked: false },
        { id: "scp-boiler-general-alarm-11012", label: "Boiler General Alarm", type: "check", defaultChecked: true },
        { id: "scp-primary-hot-water-supply-temp-11030", label: "Primary Hot Water Supply Temp", type: "check", defaultChecked: false },
        { id: "scp-primary-hot-water-return-temp-11031", label: "Primary Hot Water Return Temp", type: "check", defaultChecked: false },
      ],
    },
    {
      id: "scp-general-options-11300",
      label: "General Options",
      scope: "optional-hardware",
      required: false,
      items: [
        { id: "scp-outdoor-air-temperature-11316", label: "Outdoor Air Temperature", type: "check", defaultChecked: false },
        { id: "scp-outdoor-air-humidity-11317", label: "Outdoor Air Humidity", type: "check", defaultChecked: false },
        { id: "scp-mechanical-room-temperature-11318", label: "Mechanical Room Temperature", type: "check", defaultChecked: false },
      ],
    },
  ],
};
