export const T = {
  bg:         "var(--t-bg)",
  surface:    "var(--t-surface)",
  panel:      "var(--t-panel)",
  border:     "var(--t-border)",
  border2:    "var(--t-border2)",
  text:       "var(--t-text)",
  muted:      "var(--t-muted)",
  dim:        "var(--t-dim)",
  faint:      "var(--t-faint)",
  blue:       "var(--t-blue)",
  blueL:      "var(--t-blue-l)",
  blueFaint:  "var(--t-blue-faint)",
  blueMid:    "var(--t-blue-mid)",
  blueMidA60: "var(--t-blue-mid-a60)",
  blueA18:    "var(--t-blue-a18)",
  steel:      "var(--t-steel)",
  green:      "var(--t-green)",
  amber:      "var(--t-amber)",
  purple:     "var(--t-purple)",
  teal:       "var(--t-teal)",
  rose:       "var(--t-rose)",
  cyan:       "var(--t-cyan)",
  mono:       "'IBM Plex Mono','Courier New',monospace",
  sans:       "'IBM Plex Sans',system-ui,sans-serif",
};

export const CAT_COLOR = {
  Controls:    "#2563EB",
  Actuators:   "#0D9488",
  Pressure:    "#059669",
  Temperature: "#D97706",
  Humidity:    "#7C3AED",
  "Air Quality":"#0891B2",
  Drives:      "#9333EA",
  Safety:      "#E11D48",
  Wiring:      "#475569",
  Custom:      "#DC2626",
};
