begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

alter table public.change_orders
  add column if not exists cor_number text,
  add column if not exists sequence_number integer,
  add column if not exists number_prefix text not null default 'COR',
  add column if not exists number_padding integer not null default 4,
  add column if not exists pricing_mode text not null default 'quick_total',
  add column if not exists requested_amount numeric(12,2) not null default 0,
  add column if not exists approved_amount numeric(12,2) not null default 0,
  add column if not exists requested_days integer not null default 0,
  add column if not exists approved_days integer not null default 0,
  add column if not exists requested_by_name text,
  add column if not exists customer_contact_name text,
  add column if not exists customer_contact_email text,
  add column if not exists source text,
  add column if not exists what_happened text,
  add column if not exists work_required text,
  add column if not exists reason text,
  add column if not exists terms_note text,
  add column if not exists status_reason text,
  add column if not exists internal_notes text,
  add column if not exists submitted_at timestamptz,
  add column if not exists approved_at timestamptz,
  add column if not exists executed_at timestamptz,
  add column if not exists billed_at timestamptz,
  add column if not exists paid_at timestamptz,
  add column if not exists voided_at timestamptz,
  add column if not exists rejected_at timestamptz,
  add column if not exists superseded_at timestamptz,
  add column if not exists combined_at timestamptz,
  add column if not exists superseded_by_change_order_id uuid references public.change_orders(id) on delete set null,
  add column if not exists combined_into_change_order_id uuid references public.change_orders(id) on delete set null,
  add column if not exists modified_by uuid references public.profiles(id) on delete set null,
  add column if not exists labor_amount numeric(12,2) not null default 0,
  add column if not exists material_amount numeric(12,2) not null default 0,
  add column if not exists equipment_amount numeric(12,2) not null default 0,
  add column if not exists subcontractor_amount numeric(12,2) not null default 0,
  add column if not exists other_amount numeric(12,2) not null default 0;

comment on column public.change_orders.cor_number is 'Primary project-scoped change order number generated by the database.';
comment on column public.change_orders.co_number is 'Legacy change order number kept populated for backward compatibility.';
comment on column public.change_orders.sequence_number is 'Project-local sequence number used to generate COR numbers.';
comment on column public.change_orders.pricing_mode is 'quick_total or detailed.';
comment on column public.change_orders.internal_notes is 'Internal-only notes hidden from customer-facing output.';
comment on column public.change_orders.terms_note is 'Customer-facing terms note rendered on printable reports.';
comment on column public.change_orders.what_happened is 'Narrative of what happened for the change event.';
comment on column public.change_orders.work_required is 'Narrative of the work required.';
comment on column public.change_orders.reason is 'Reason or source for the change.';
comment on column public.change_orders.status_reason is 'Required explanation for voided, rejected, and superseded actions.';

alter table public.change_orders
  drop constraint if exists change_orders_pricing_mode_check;
alter table public.change_orders
  add constraint change_orders_pricing_mode_check
  check (pricing_mode in ('quick_total', 'detailed'));

alter table public.change_orders
  drop constraint if exists change_orders_requested_days_check;
alter table public.change_orders
  add constraint change_orders_requested_days_check
  check (requested_days between -3650 and 3650);

alter table public.change_orders
  drop constraint if exists change_orders_approved_days_check;
alter table public.change_orders
  add constraint change_orders_approved_days_check
  check (approved_days between -3650 and 3650);

alter table public.change_orders
  drop constraint if exists change_orders_number_padding_check;
alter table public.change_orders
  add constraint change_orders_number_padding_check
  check (number_padding between 2 and 8);

create table if not exists public.project_change_order_sequences (
  project_id uuid primary key references public.projects(id) on delete cascade,
  next_sequence integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.project_change_order_sequences is 'Per-project sequence reservation counter for change order numbering.';

drop trigger if exists trg_project_change_order_sequences_updated_at on public.project_change_order_sequences;
create trigger trg_project_change_order_sequences_updated_at
  before update on public.project_change_order_sequences
  for each row execute function public.set_updated_at();

create or replace function public.reserve_project_change_order_number(
  p_project_id uuid,
  p_prefix text default 'COR',
  p_padding integer default 4
)
returns table(sequence_number integer, cor_number text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sequence integer;
  v_prefix text := coalesce(nullif(btrim(p_prefix), ''), 'COR');
  v_padding integer := greatest(coalesce(p_padding, 4), 2);
begin
  insert into public.project_change_order_sequences (project_id, next_sequence)
  values (p_project_id, 1)
  on conflict (project_id) do nothing;

  update public.project_change_order_sequences
     set next_sequence = next_sequence + 1
   where project_id = p_project_id
   returning next_sequence - 1 into v_sequence;

  sequence_number := v_sequence;
  cor_number := v_prefix || '-' || lpad(v_sequence::text, v_padding, '0');
  return next;
end;
$$;

revoke all on function public.reserve_project_change_order_number(uuid, text, integer) from public;
grant execute on function public.reserve_project_change_order_number(uuid, text, integer) to authenticated;

create or replace function public.normalize_change_order_status(input_status text)
returns co_status
language plpgsql
immutable
as $$
begin
  case lower(coalesce(btrim(input_status), 'draft'))
    when 'pending' then return 'in_review'::co_status;
    when 'needs_revision' then return 'needs_pricing'::co_status;
    when 'approved_po' then return 'approved'::co_status;
    when 'approved_email' then return 'approved'::co_status;
    when 'void' then return 'voided'::co_status;
    when 'draft' then return 'draft'::co_status;
    when 'needs_pricing' then return 'needs_pricing'::co_status;
    when 'ready_to_submit' then return 'ready_to_submit'::co_status;
    when 'submitted' then return 'submitted'::co_status;
    when 'in_review' then return 'in_review'::co_status;
    when 'approved' then return 'approved'::co_status;
    when 'rejected' then return 'rejected'::co_status;
    when 'voided' then return 'voided'::co_status;
    when 'superseded' then return 'superseded'::co_status;
    when 'executed' then return 'executed'::co_status;
    when 'billed' then return 'billed'::co_status;
    when 'paid' then return 'paid'::co_status;
    else return 'draft'::co_status;
  end case;
end;
$$;

create or replace function public.normalize_change_orders_v1()
returns trigger
language plpgsql
as $$
declare
  v_reserved record;
  v_effective_amount numeric(12,2);
begin
  new.status := public.normalize_change_order_status(coalesce(new.status::text, 'draft'));

  if tg_op = 'INSERT' then
    if new.sequence_number is null or new.cor_number is null or btrim(coalesce(new.cor_number, '')) = '' then
      select * into v_reserved
      from public.reserve_project_change_order_number(
        new.project_id,
        coalesce(nullif(btrim(new.number_prefix), ''), 'COR'),
        coalesce(new.number_padding, 4)
      )
      limit 1;

      new.sequence_number := v_reserved.sequence_number;
      new.cor_number := v_reserved.cor_number;
    end if;
  end if;

  if btrim(coalesce(new.co_number, '')) = '' then
    new.co_number := new.cor_number;
  end if;

  if new.number_prefix is null or btrim(new.number_prefix) = '' then
    new.number_prefix := 'COR';
  end if;

  if new.number_padding is null or new.number_padding < 2 then
    new.number_padding := 4;
  end if;

  v_effective_amount := coalesce(nullif(new.requested_amount, 0), new.amount, 0);
  new.requested_amount := v_effective_amount;
  new.amount := v_effective_amount;

  if new.status::text = 'submitted' and new.submitted_at is null then
    new.submitted_at := now();
  end if;

  if new.status::text = 'approved' and new.approved_at is null then
    new.approved_at := now();
  end if;

  if new.status::text = 'executed' and new.executed_at is null then
    new.executed_at := now();
  end if;

  if new.status::text = 'billed' and new.billed_at is null then
    new.billed_at := now();
  end if;

  if new.status::text = 'paid' and new.paid_at is null then
    new.paid_at := now();
  end if;

  if new.status::text = 'voided' and new.voided_at is null then
    new.voided_at := now();
  end if;

  if new.status::text = 'rejected' and new.rejected_at is null then
    new.rejected_at := now();
  end if;

  if new.status::text = 'superseded' and new.superseded_at is null then
    new.superseded_at := now();
  end if;

  new.updated_at := now();
  return new;
end;
$$;

create or replace function public.recalculate_change_order_totals(p_change_order_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_requested_amount numeric(12,2);
  v_labor_amount numeric(12,2);
  v_material_amount numeric(12,2);
  v_equipment_amount numeric(12,2);
  v_subcontractor_amount numeric(12,2);
  v_other_amount numeric(12,2);
begin
  select
    coalesce(sum(total), 0)::numeric(12,2),
    coalesce(sum(total) filter (where category = 'labor'), 0)::numeric(12,2),
    coalesce(sum(total) filter (where category = 'material'), 0)::numeric(12,2),
    coalesce(sum(total) filter (where category = 'equipment'), 0)::numeric(12,2),
    coalesce(sum(total) filter (where category = 'subcontractor'), 0)::numeric(12,2),
    coalesce(sum(total) filter (where category = 'other'), 0)::numeric(12,2)
  into
    v_requested_amount,
    v_labor_amount,
    v_material_amount,
    v_equipment_amount,
    v_subcontractor_amount,
    v_other_amount
  from public.change_order_line_items
  where change_order_id = p_change_order_id;

  update public.change_orders
     set requested_amount = v_requested_amount,
         amount = v_requested_amount,
         labor_amount = v_labor_amount,
         material_amount = v_material_amount,
         equipment_amount = v_equipment_amount,
         subcontractor_amount = v_subcontractor_amount,
         other_amount = v_other_amount,
         updated_at = now()
   where id = p_change_order_id;
end;
$$;

create or replace function public.normalize_change_order_line_item()
returns trigger
language plpgsql
as $$
declare
  v_base numeric(12,2);
  v_markup numeric(12,2);
begin
  if new.category not in ('labor', 'material', 'equipment', 'subcontractor', 'other') then
    raise exception 'Invalid change order line item category: %', new.category;
  end if;

  v_markup := coalesce(new.markup_percent, 0);

  if new.category = 'labor' then
    v_base := coalesce(new.people_count, 0) * coalesce(new.hours_per_person, 0) * coalesce(new.days, 0) * coalesce(new.hourly_rate, 0);
  elsif new.lump_sum is not null then
    v_base := coalesce(new.lump_sum, 0);
  else
    v_base := coalesce(new.quantity, 0) * coalesce(new.unit_cost, 0);
  end if;

  new.base_amount := round(v_base::numeric, 2);
  new.total := round((v_base * (1 + (v_markup / 100)))::numeric, 2);
  new.updated_at := now();
  return new;
end;
$$;

create or replace function public.recalculate_change_order_totals_trigger()
returns trigger
language plpgsql
as $$
declare
  v_change_order_id uuid;
begin
  if tg_op = 'DELETE' then
    v_change_order_id := old.change_order_id;
  else
    v_change_order_id := new.change_order_id;
  end if;

  perform public.recalculate_change_order_totals(v_change_order_id);
  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;

create table if not exists public.change_order_line_items (
  id uuid primary key default gen_random_uuid(),
  change_order_id uuid not null references public.change_orders(id) on delete cascade,
  category text not null,
  sort_order integer not null default 0,
  description text not null,
  role text,
  people_count numeric(12,2),
  hours_per_person numeric(12,2),
  days numeric(12,2),
  hourly_rate numeric(12,2),
  quantity numeric(12,2),
  unit text,
  unit_cost numeric(12,2),
  lump_sum numeric(12,2),
  markup_percent numeric(12,2) not null default 0,
  base_amount numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.change_order_line_items is 'Calculator-ready change order line items.';
create index if not exists idx_change_order_line_items_change_order_sort
  on public.change_order_line_items(change_order_id, sort_order, created_at);

drop trigger if exists trg_change_order_line_items_updated_at on public.change_order_line_items;
create trigger trg_change_order_line_items_updated_at
  before update on public.change_order_line_items
  for each row execute function public.set_updated_at();

drop trigger if exists trg_change_order_line_items_recalc_ins on public.change_order_line_items;
create trigger trg_change_order_line_items_recalc_ins
  after insert on public.change_order_line_items
  for each row execute function public.recalculate_change_order_totals_trigger();

drop trigger if exists trg_change_order_line_items_recalc_upd on public.change_order_line_items;
create trigger trg_change_order_line_items_recalc_upd
  after update on public.change_order_line_items
  for each row execute function public.recalculate_change_order_totals_trigger();

drop trigger if exists trg_change_order_line_items_recalc_del on public.change_order_line_items;
create trigger trg_change_order_line_items_recalc_del
  after delete on public.change_order_line_items
  for each row execute function public.recalculate_change_order_totals_trigger();

create table if not exists public.change_order_attachments (
  id uuid primary key default gen_random_uuid(),
  change_order_id uuid not null references public.change_orders(id) on delete cascade,
  attachment_kind text not null default 'backup',
  title text,
  description text,
  file_name text not null,
  content_type text,
  storage_provider text not null default 'onedrive',
  storage_path text,
  storage_web_url text,
  file_size_bytes bigint,
  sort_order integer not null default 0,
  is_customer_visible boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.change_order_attachments is 'Attachment metadata for change orders. The binary file lives in external storage.';
create index if not exists idx_change_order_attachments_change_order_sort
  on public.change_order_attachments(change_order_id, sort_order, created_at);

create index if not exists idx_change_order_attachments_customer_visible
  on public.change_order_attachments(change_order_id, is_customer_visible);

drop trigger if exists trg_change_order_attachments_updated_at on public.change_order_attachments;
create trigger trg_change_order_attachments_updated_at
  before update on public.change_order_attachments
  for each row execute function public.set_updated_at();

create table if not exists public.change_order_status_history (
  id uuid primary key default gen_random_uuid(),
  change_order_id uuid not null references public.change_orders(id) on delete cascade,
  previous_status co_status,
  new_status co_status not null,
  reason text,
  changed_by uuid references public.profiles(id) on delete set null,
  changed_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

comment on table public.change_order_status_history is 'Auditable change order status history.';
create index if not exists idx_change_order_status_history_change_order_changed_at
  on public.change_order_status_history(change_order_id, changed_at desc);

create or replace function public.log_change_order_status_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.change_order_status_history (
      change_order_id,
      previous_status,
      new_status,
      reason,
      changed_by,
      changed_at,
      metadata
    )
    values (
      new.id,
      null,
      new.status,
      new.status_reason,
      new.modified_by,
      now(),
      jsonb_build_object('event', 'insert')
    );
    return new;
  end if;

  if old.status is distinct from new.status then
    insert into public.change_order_status_history (
      change_order_id,
      previous_status,
      new_status,
      reason,
      changed_by,
      changed_at,
      metadata
    )
    values (
      new.id,
      old.status,
      new.status,
      new.status_reason,
      new.modified_by,
      now(),
      jsonb_build_object(
        'event', 'status_change',
        'old_status_reason', old.status_reason,
        'new_status_reason', new.status_reason
      )
    );
  end if;

  return new;
end;
$$;

with ranked as (
  select
    id,
    project_id,
    row_number() over (
      partition by project_id
      order by created_at asc, id asc
    ) as rn
  from public.change_orders
)
update public.change_orders co
   set sequence_number = coalesce(co.sequence_number, ranked.rn),
       cor_number = coalesce(
         nullif(btrim(co.cor_number), ''),
         coalesce(
           case
             when co.sequence_number is not null then co.number_prefix || '-' || lpad(co.sequence_number::text, coalesce(co.number_padding, 4), '0')
             else null
           end,
           co.number_prefix || '-' || lpad(ranked.rn::text, coalesce(co.number_padding, 4), '0')
         )
       ),
       co_number = coalesce(nullif(btrim(co.co_number), ''), coalesce(nullif(btrim(co.cor_number), ''), co.number_prefix || '-' || lpad(ranked.rn::text, coalesce(co.number_padding, 4), '0')))
  from ranked
 where co.id = ranked.id
   and (
     co.sequence_number is null
     or co.cor_number is null
     or btrim(co.cor_number) = ''
     or co.co_number is null
     or btrim(co.co_number) = ''
   );

insert into public.project_change_order_sequences (project_id, next_sequence)
select
  project_id,
  greatest(coalesce(max(sequence_number), 0) + 1, 1)
from public.change_orders
group by project_id
on conflict (project_id) do update
set next_sequence = greatest(public.project_change_order_sequences.next_sequence, excluded.next_sequence),
    updated_at = now();

update public.change_orders
   set status = public.normalize_change_order_status(status::text),
       updated_at = now()
 where status::text in ('pending', 'needs_revision', 'approved_po', 'approved_email', 'void');

update public.change_orders
   set requested_amount = coalesce(nullif(requested_amount, 0), amount, 0),
       amount = coalesce(nullif(requested_amount, 0), amount, 0),
       co_number = coalesce(nullif(btrim(co_number), ''), cor_number),
       updated_at = now()
 where true;

insert into public.change_order_status_history (
  change_order_id,
  previous_status,
  new_status,
  reason,
  changed_by,
  changed_at,
  metadata
)
select
  id,
  null,
  status,
  status_reason,
  modified_by,
  created_at,
  jsonb_build_object('event', 'backfill')
from public.change_orders
where not exists (
  select 1
  from public.change_order_status_history h
  where h.change_order_id = public.change_orders.id
);

alter table public.change_orders
  alter column status set default 'draft'::co_status,
  alter column cor_number set not null,
  alter column sequence_number set not null,
  alter column co_number set not null;

create unique index if not exists uq_change_orders_project_cor_number
  on public.change_orders(project_id, cor_number);

create unique index if not exists uq_change_orders_project_sequence_number
  on public.change_orders(project_id, sequence_number);

create index if not exists idx_change_orders_project_status_sequence
  on public.change_orders(project_id, status, sequence_number desc);

drop trigger if exists trg_change_orders_normalize_v1 on public.change_orders;
create trigger trg_change_orders_normalize_v1
  before insert or update on public.change_orders
  for each row execute function public.normalize_change_orders_v1();

drop trigger if exists trg_change_order_status_history on public.change_orders;
create trigger trg_change_order_status_history
  after insert or update on public.change_orders
  for each row execute function public.log_change_order_status_history();

commit;
